package org.churchpresenter.helper.intent.glossary

internal val POLISH = Glossary(
    "pl",
    listOf(
        // Asking where, or how.
        "gdzie" to "where",
        "dokąd" to "where",
        "dokad" to "where",
        "jak mogę" to "how can i",
        "jak moge" to "how can i",
        "jak można" to "how can i",
        "jak mozna" to "how can i",
        "w jaki sposób" to "how do i",
        "w jaki sposob" to "how do i",
        "jak" to "how do i",
        "nie mogę znaleźć" to "can't find",
        "nie moge znalezc" to "can't find",
        "nie mogę znaleść" to "can't find",
        "nie znajduję" to "can't find",
        "nie znajduje" to "can't find",
        "pokaż mi" to "show me",
        "pokaz mi" to "show me",
        "podpowiedz" to "how do i",

        // Doing.
        "pokaż" to "show",
        "pokaz" to "show",
        "pokazać" to "show",
        "pokazac" to "show",
        "pokażcie" to "show",
        "pokazcie" to "show",
        "pokazuj" to "show",
        "wyświetl*" to "display",
        "wyswietl*" to "display",
        "otwórz" to "open",
        "otworz" to "open",
        "otworzyć" to "open",
        "otworzyc" to "open",
        "przejdź do" to "go to",
        "przejdz do" to "go to",
        "przejść do" to "go to",
        "przejsc do" to "go to",
        "idź do" to "go to",
        "idz do" to "go to",
        "przełącz na" to "switch to",
        "przelacz na" to "switch to",
        "przełącz się na" to "switch to",
        "przelacz sie na" to "switch to",
        "znajdź" to "find",
        "znajdz" to "find",
        "znaleźć" to "find",
        "znalezc" to "find",
        "wyszukaj" to "find",
        "przeczytaj" to "read",
        "zrób" to "make",
        "zrob" to "make",
        "zrobić" to "make",
        "zrobic" to "make",
        "utwórz" to "create",
        "utworz" to "create",
        "utworzyć" to "create",
        "utworzyc" to "create",
        "stwórz" to "create",
        "stworz" to "create",
        "dodaj*" to "add",
        "dodać" to "add",
        "dodac" to "add",
        "wczytaj*" to "load",
        "załaduj*" to "load",
        "zaladuj*" to "load",
        "importuj*" to "import",
        "zaimportuj*" to "import",
        "pobierz*" to "download",
        "pobrać" to "download",
        "pobrac" to "download",
        "zainstaluj*" to "install",
        "wybierz*" to "choose",
        "wybrać" to "choose",
        "wybrac" to "choose",
        "skonfiguruj*" to "set up",
        "konfiguruj*" to "set up",
        "ustaw*" to "set up",
        "podłącz*" to "connect",
        "podlacz*" to "connect",
        "połącz*" to "connect",
        "polacz*" to "connect",
        "przypisz*" to "assign",
        "ukryj*" to "hide",
        "schowaj*" to "hide",
        "zatrzymaj*" to "stop",
        "usuń" to "delete",
        "usun" to "delete",
        "usunąć" to "delete",
        "usunac" to "delete",
        "wyczyść" to "clear",
        "wyczysc" to "clear",
        "wyczyścić" to "clear",
        "wyczyscic" to "clear",
        "zaciemnij*" to "black out",
        "wygaś ekran" to "black out",
        "wygas ekran" to "black out",
        "pusty ekran" to "blank",
        "cofnij*" to "undo",
        "przywróć jak było" to "undo",
        "przywroc jak bylo" to "undo",
        "na żywo" to "go live",
        "na zywo" to "go live",
        "puść na żywo" to "go live",
        "pusc na zywo" to "go live",
        "włącz*" to "turn on",
        "wlacz*" to "turn on",
        "wyłącz*" to "turn off",
        "wylacz*" to "turn off",
        "przełącz*" to "toggle",
        "przelacz*" to "toggle",
        "następn*" to "next",
        "nastepn*" to "next",
        "dalej" to "next",
        "naprzód" to "forward",
        "naprzod" to "forward",
        "poprzedni*" to "previous",
        "wstecz" to "back",
        "wróć" to "back",
        "wroc" to "back",
        "powiększ*" to "increase",
        "powieksz*" to "increase",
        "zwiększ*" to "increase",
        "zwieksz*" to "increase",
        "większ*" to "bigger",
        "wieksz*" to "bigger",
        "zmniejsz*" to "decrease",
        "pomniejsz*" to "decrease",
        "mniejsz*" to "smaller",
        "konwertuj*" to "convert",
        "przekonwertuj*" to "convert",
        "konwerter*" to "converter",
        "przenieś" to "transfer",
        "przenies" to "transfer",
        "przenieść" to "transfer",
        "przeniesc" to "transfer",
        "edytuj*" to "edit",
        "zmień nazwę" to "rename",
        "zmien nazwe" to "rename",
        "zmień" to "change",
        "zmien" to "change",
        "zmienić" to "change",
        "zmienic" to "change",
        "napraw*" to "fix",
        "popraw*" to "fix",
        "uporządkuj*" to "organize",
        "uporzadkuj*" to "organize",
        "zorganizuj*" to "organize",
        "posprzątaj" to "clean up",
        "posprzataj" to "clean up",
        "porównaj*" to "compare",
        "porownaj*" to "compare",
        "przetłumacz*" to "translate",
        "przetlumacz*" to "translate",
        "zaplanuj*" to "plan",
        "planuj*" to "plan",
        "zautomatyzuj*" to "automate",
        "automatyzuj*" to "automate",
        "automatyczn*" to "automatically",
        "zidentyfikuj*" to "identify",
        "ponumeruj*" to "number the",

        // Too small, too big, not working.
        "za mał*" to "too small",
        "za mal*" to "too small",
        "zbyt mał*" to "too small",
        "zbyt mal*" to "too small",
        "słabo widać" to "hard to read",
        "slabo widac" to "hard to read",
        "nie widać" to "hard to read",
        "nie widac" to "hard to read",
        "trudno przeczytać" to "hard to read",
        "trudno przeczytac" to "hard to read",
        "nieczyteln*" to "hard to read",
        "za duż*" to "too big",
        "za duz*" to "too big",
        "zbyt duż*" to "too big",
        "zbyt duz*" to "too big",
        "nie mieści się" to "doesn't fit",
        "nie miesci sie" to "doesn't fit",
        "nie działa" to "not working",
        "nie dziala" to "not working",
        "nie pokazuje" to "not showing",
        "nic nie pokazuje" to "nothing shows",
        "nic nie ma" to "nothing shows",
        "czarny ekran" to "screen is black",
        "brak sygnału" to "no signal",
        "brak sygnalu" to "no signal",
        "brak obrazu" to "no picture",
        "który ekran" to "which screen",
        "ktory ekran" to "which screen",
        "który monitor" to "which monitor",
        "ktory monitor" to "which monitor",
        "który projektor" to "which projector",
        "ktory projektor" to "which projector",

        // What is on screen.
        "tło" to "background",
        "tlo" to "background",
        "tła" to "background",
        "tla" to "background",
        "tłem" to "background",
        "tlem" to "background",
        "tle" to "background",
        "tłu" to "background",
        "tlu" to "background",
        "tekst piosenki" to "lyrics",
        "tekst pieśni" to "lyrics",
        "tekst piesni" to "lyrics",
        "słowa piosenki" to "lyrics",
        "slowa piosenki" to "lyrics",
        "słowa pieśni" to "lyrics",
        "slowa piesni" to "lyrics",
        "pieśń nad pieśniami" to "pieśń nad pieśniami",
        "piesn nad piesniami" to "piesn nad piesniami",
        "księga wyjścia" to "księga wyjścia",
        "ksiega wyjscia" to "ksiega wyjscia",
        "powtórzonego prawa" to "powtórzonego prawa",
        "powtorzonego prawa" to "powtorzonego prawa",
        "piosenek" to "songs",
        "piosenk*" to "song",
        "pieśń" to "song",
        "piesn" to "song",
        "pieśni" to "songs",
        "piesni" to "songs",
        "pieśnią" to "song",
        "piesnia" to "song",
        "uwielbieni*" to "worship",
        "bibli*" to "bible",
        "pismo święte" to "scripture",
        "pismo swiete" to "scripture",
        "pisma świętego" to "scripture",
        "pisma swietego" to "scripture",
        "werset*" to "verse",
        "wiersz*" to "verse",
        "rozdział" to "chapter",
        "rozdzial" to "chapter",
        "rozdziału" to "chapter",
        "rozdzialu" to "chapter",
        "czcionk*" to "font",
        "rozmiar*" to "size",
        "tekst*" to "text",
        "słowa" to "words",
        "slowa" to "words",
        "liter*" to "letters",
        "pokaz slajdów" to "slideshow",
        "pokaz slajdow" to "slideshow",
        "slajd*" to "slide",
        "zdjęci*" to "photo",
        "zdjeci*" to "photo",
        "fotografi*" to "photo",
        "fotk*" to "photo",
        "obraz*" to "picture",
        "grafik*" to "image",
        "album*" to "album",
        "prezentacj*" to "presentation",
        "wideo" to "video",
        "filmik*" to "clip",
        "film*" to "movie",
        "klip*" to "clip",
        "multimedi*" to "media",
        "dźwięk*" to "audio",
        "dzwiek*" to "audio",
        "dolna trzecia" to "lower third",
        "dolnej trzeciej" to "lower third",
        "dolna belka" to "lower third",
        "dolny pasek" to "lower third",
        "belka z imieniem" to "name strap",
        "podpis z imieniem" to "name strap",
        "imię i funkcja" to "name and title",
        "imie i funkcja" to "name and title",
        "ogłoszeni*" to "announcement",
        "ogloszeni*" to "announcement",
        "komunikat*" to "announcement",
        "przewijany tekst" to "ticker",
        "pasek informacyjny" to "ticker",
        "pokój dziecięcy" to "kids room",
        "pokoj dzieciecy" to "kids room",
        "sala dla dzieci" to "kids room",
        "odliczani*" to "countdown",
        "minutnik*" to "timer",
        "stoper*" to "stopwatch",
        "zegar*" to "clock",
        "aktualna godzina" to "current time",
        "aktualny czas" to "current time",
        "godzina" to "time",
        "czas" to "time",
        "notatk*" to "notes",
        "akord*" to "chord",
        "tłumaczeni*" to "translation",
        "tlumaczeni*" to "translation",
        "przekład*" to "translation",
        "przeklad*" to "translation",
        "język*" to "language",
        "jezyk*" to "language",
        "dwujęzyczn*" to "bilingual",
        "dwujezyczn*" to "bilingual",
        "w innym języku" to "another language",
        "w innym jezyku" to "another language",
        "inny język" to "another language",
        "inny jezyk" to "another language",
        "drugi język" to "second language",
        "drugi jezyk" to "second language",
        "w dwóch językach" to "two languages",
        "w dwoch jezykach" to "two languages",

        // Screens and outputs.
        "główny ekran" to "main screen",
        "glowny ekran" to "main screen",
        "głównym ekranie" to "main screen",
        "glownym ekranie" to "main screen",
        "pełny ekran" to "full screen",
        "pelny ekran" to "full screen",
        "pełnym ekranie" to "full screen",
        "pelnym ekranie" to "full screen",
        "na cały ekran" to "full screen",
        "na caly ekran" to "full screen",
        "pełnoekranow*" to "fullscreen",
        "pelnoekranow*" to "fullscreen",
        "drugi ekran" to "second screen",
        "drugim ekranie" to "second screen",
        "ekran*" to "screen",
        "projektor*" to "projector",
        "rzutnik*" to "projector",
        "monitor sceny" to "stage monitor",
        "monitora sceny" to "stage monitor",
        "monitor na scenie" to "stage monitor",
        "monitor dla sceny" to "stage monitor",
        "monitor sceniczny" to "stage monitor",
        "monitor odsłuchowy" to "stage monitor",
        "monitor odsluchowy" to "stage monitor",
        "sufler*" to "confidence monitor",
        "monitor*" to "monitor",
        "wyświetlacz*" to "display",
        "wyswietlacz*" to "display",
        "okno wyjściowe" to "output window",
        "okno wyjsciowe" to "output window",
        "okno wyjścia" to "output window",
        "okno wyjscia" to "output window",
        "wyjście" to "output",
        "wyjscie" to "output",
        "wyjściu" to "output",
        "wyjsciu" to "output",
        "wyjściem" to "output",
        "wyjsciem" to "output",
        "wyjść" to "output",
        "wyjsc" to "output",
        "wyjściowy" to "output",
        "wyjsciowy" to "output",
        "wyjściowe" to "output",
        "wyjsciowe" to "output",
        "projekcj*" to "projection",
        "scena" to "stage",
        "sceny" to "stage",
        "scenie" to "stage",
        "scenę" to "stage",
        "sceną" to "stage",
        "scenicz*" to "stage",
        "stref*" to "zone",
        "układ*" to "layout",
        "uklad*" to "layout",
        "rozmieszczeni*" to "arrangement",
        "wiadomoś*" to "message",
        "wiadomos*" to "message",
        "wyślij*" to "send",
        "wyslij*" to "send",
        "wysłać" to "send",
        "wyslac" to "send",
        "podgląd*" to "preview",
        "podglad*" to "preview",
        "co jest na ekranie" to "what is on screen",
        "profil*" to "profile",
        "transmisj*" to "stream",
        "telewizor*" to "tv",

        // Pages, tabs and tools.
        "ustawieni*" to "settings",
        "opcj*" to "options",
        "kreator konfiguracji" to "setup wizard",
        "pierwsze kroki" to "setup wizard",
        "zacznij od nowa" to "start over",
        "od nowa" to "start over",
        "skrót klawiszowy" to "shortcut",
        "skrot klawiszowy" to "shortcut",
        "skróty klawiszowe" to "shortcut",
        "skroty klawiszowe" to "shortcut",
        "skrót*" to "shortcut",
        "skrot*" to "shortcut",
        "klawiatur*" to "keyboard",
        "zakładk*" to "tab",
        "zakladk*" to "tab",
        "kart*" to "tab",
        "biblioteka piosenek" to "song library",
        "biblioteka pieśni" to "song library",
        "biblioteka piesni" to "song library",
        "bibliotece pieśni" to "song library",
        "bibliotece piesni" to "song library",
        "bibliotek*" to "library",
        "strona internetowa" to "website",
        "stronę internetową" to "website",
        "strone internetowa" to "website",
        "przeglądark*" to "browser",
        "przegladark*" to "browser",
        "słownik*" to "dictionary",
        "slownik*" to "dictionary",
        "kamer*" to "camera",
        "płótn*" to "canvas",
        "plotn*" to "canvas",
        "serwer*" to "server",
        "zdaln*" to "remote",
        "pilot*" to "remote",
        "telefon*" to "phone",
        "komórk*" to "phone",
        "komork*" to "phone",
        "integracj*" to "integrations",

        // Services and planning.
        "porządek nabożeństwa" to "order of service",
        "porzadek nabozenstwa" to "order of service",
        "program nabożeństwa" to "order of service",
        "program nabozenstwa" to "order of service",
        "przebieg nabożeństwa" to "order of service",
        "przebieg nabozenstwa" to "order of service",
        "nabożeńst*" to "service",
        "nabozenst*" to "service",
        "spotkani*" to "meeting",
        "niedziel*" to "sunday",
        "kalendarz*" to "calendar",
        "harmonogram*" to "schedule",
        "lista odtwarzania" to "playlist",
        "w każdą niedzielę" to "every sunday",
        "w kazda niedziele" to "every sunday",
        "co niedzielę" to "every sunday",
        "co niedziele" to "every sunday",
        "co tydzień" to "every week",
        "co tydzien" to "every week",
        "cotygodniow*" to "weekly",
        "tygodniow*" to "weekly",
        "comiesięczn*" to "monthly",
        "comiesieczn*" to "monthly",
        "miesięczn*" to "monthly",
        "miesieczn*" to "monthly",
        "powtarza*" to "repeat",
        "powtórz*" to "repeat",
        "powtorz*" to "repeat",
        "szablon*" to "template",

        // Many, all, both.
        "wszystk*" to "all",
        "wszędzie" to "everything",
        "wszedzie" to "everything",
        "oba" to "both",
        "obie" to "both",
        "obydwa" to "both",
        "obu" to "both",
        "kilka" to "several",
        "kilku" to "several",
        "wiele" to "many",
        "dużo" to "many",
        "duzo" to "many",
        "naraz" to "at once",
        "jednocześnie" to "at once",
        "jednoczesnie" to "at once",
        "na to nabożeństwo" to "this service",
        "na to nabozenstwo" to "this service",
        "na dziś" to "for today",
        "na dzis" to "for today",
        "na dzisiaj" to "for today",
        "tymczasowo" to "temporarily",

        // Languages, by name.
        "rosyjsk*" to "russian",
        "ukraińsk*" to "ukrainian",
        "ukrainsk*" to "ukrainian",
        "białorusk*" to "belarusian",
        "bialorusk*" to "belarusian",
        "angielsk*" to "english",
        "hiszpańsk*" to "spanish",
        "hiszpansk*" to "spanish",
        "niemieck*" to "german",
        "francusk*" to "french",
        "polsk*" to "polish",
        "czesk*" to "czech",
        "słowack*" to "slovak",
        "slowack*" to "slovak",
        "chorwack*" to "croatian",
        "serbsk*" to "serbian",
        "portugalsk*" to "portuguese",
        "włosk*" to "italian",
        "wlosk*" to "italian",
        "kazachsk*" to "kazakh",
        "rumuńsk*" to "romanian",
        "rumunsk*" to "romanian",
        "mołdawsk*" to "moldovan",
        "moldawsk*" to "moldovan",
        "łacin*" to "latin",
        "lacin*" to "latin",

        // Colors.
        "granatow*" to "navy",
        "ciemnoniebiesk*" to "navy",
        "jasnoniebiesk*" to "light blue",
        "błękitn*" to "light blue",
        "blekitn*" to "light blue",
        "niebiesk*" to "blue",
        "czarn*" to "black",
        "biał*" to "white",
        "bial*" to "white",
        "szary" to "grey",
        "szara" to "grey",
        "szare" to "grey",
        "szarym" to "grey",
        "szarą" to "grey",
        "szaro" to "grey",
        "szarego" to "grey",
        "szarej" to "grey",
        "srebrn*" to "silver",
        "czerwon*" to "red",
        "bordow*" to "maroon",
        "pomarańczow*" to "orange",
        "pomaranczow*" to "orange",
        "żółt*" to "yellow",
        "zolt*" to "yellow",
        "złot*" to "gold",
        "zlot*" to "gold",
        "zielon*" to "green",
        "limonkow*" to "lime",
        "turkusow*" to "turquoise",
        "fioletow*" to "purple",
        "liliow*" to "violet",
        "różow*" to "pink",
        "rozow*" to "pink",
        "brązow*" to "brown",
        "brazow*" to "brown",
        "beżow*" to "beige",
        "bezow*" to "beige",
        "kremow*" to "cream",
        "ciemn*" to "dark",
        "jasn*" to "light",

        // Talking to the helper.
        "cześć" to "hello",
        "czesc" to "hello",
        "dzień dobry" to "hello",
        "dzien dobry" to "hello",
        "witaj*" to "hello",
        "pomóż*" to "help",
        "pomoz*" to "help",
        "pomocy" to "help",
        "pomoc" to "help",
        "co potrafisz" to "what can you do",
        "co umiesz" to "what can you do",
        "co możesz" to "what can you do",
        "co mozesz" to "what can you do",
        "kim jesteś" to "who are you",
        "kim jestes" to "who are you",
        "dziękuję" to "thank you",
        "dziekuje" to "thank you",
        "dzięki" to "thanks",
        "dzieki" to "thanks",
        "proszę" to "please",
        "prosze" to "please",
        "wik" to "wick",
        "łik" to "wick",
        "uik" to "wick",

        // Newer requests.
        "szuka*" to "search",
        "poszuka*" to "search",
        "wyszukać" to "search",
        "wyszukac" to "search",
        "wyszukiwa*" to "search",
        "wyszukaj w" to "search in",
        "znajdź pieśń" to "find a song",
        "znajdz piesn" to "find a song",
        "znajdź piosenkę" to "find a song",
        "znajdz piosenke" to "find a song",
        "znaleźć pieśń" to "find a song",
        "znalezc piesn" to "find a song",
        "znajdź werset" to "find a verse",
        "wyszukaj werset" to "find a verse",
        "wyszukaj pieśń" to "find a song",
        "wyszukaj piesn" to "find a song",
        "wyszukaj piosenkę" to "find a song",
        "wyszukaj piosenke" to "find a song",
        "znajdz werset" to "find a verse",
        "znaleźć werset" to "find a verse",
        "znalezc werset" to "find a verse",
        "numer pieśni" to "song number",
        "numer piesni" to "song number",
        "numer piosenki" to "song number",
        "po numerze" to "by number",
        "po tytule" to "by title",
        "numer" to "number",
        "nr" to "number",
        "o nazwie" to "called",
        "o tytule" to "called",
        "pod tytułem" to "called",
        "pod tytulem" to "called",
        "ulubion*" to "favorite",
        "gwiazdk*" to "starred",
        "tej pieśni" to "this song",
        "tej piesni" to "this song",
        "tej piosenki" to "this song",
        "tej piosence" to "this song",
        "tę pieśń" to "this song",
        "te piesn" to "this song",
        "tę piosenkę" to "this song",
        "te piosenke" to "this song",
        "każdej pieśni" to "each song",
        "kazdej piesni" to "each song",
        "każdej piosenki" to "each song",
        "kazdej piosenki" to "each song",
        "własne tło" to "own background",
        "wlasne tlo" to "own background",
        "własnym tłem" to "own background",
        "wlasnym tlem" to "own background",
        "własnego tła" to "own background",
        "wlasnego tla" to "own background",
        "osobne tło" to "own background",
        "osobne tlo" to "own background",
        "kilka wersetów" to "several verses",
        "kilka wersetow" to "several verses",
        "kilku wersetów" to "several verses",
        "kilku wersetow" to "several verses",
        "wiele wersetów" to "multiple verses",
        "wiele wersetow" to "multiple verses",
        "więcej niż jeden werset" to "more than one verse",
        "wiecej niz jeden werset" to "more than one verse",
        "zakres wersetów" to "range of verses",
        "zakres wersetow" to "range of verses",
        "cały fragment" to "whole passage",
        "caly fragment" to "whole passage",
        "histori*" to "history",
        "co przed chwilą pokazaliśmy" to "what did we just show",
        "co przed chwila pokazalismy" to "what did we just show",
        "co właśnie pokazaliśmy" to "what did we just show",
        "co wlasnie pokazalismy" to "what did we just show",
        "co pokazaliśmy" to "what did we show",
        "co pokazalismy" to "what did we show",
        "ostatnie wersety" to "recent verses",
        "ostatnio pokazane" to "recently shown",
        "powiązane wersety" to "related verses",
        "powiazane wersety" to "related verses",
        "powiązane fragmenty" to "related passages",
        "powiazane fragmenty" to "related passages",
        "miejsca paralelne" to "parallel passages",
        "fragmenty paralelne" to "parallel passages",
        "odnośnik*" to "cross references",
        "odnosnik*" to "cross references",
        "odsyłacz*" to "cross references",
        "odsylacz*" to "cross references",
        "stron* www" to "website",
        "stron* internetow*" to "website",
        "witryn*" to "website",
        "adres url" to "url",
        "adres strony" to "url",
        "planning centera" to "planning center",
        "planning centerze" to "planning center",
        "planning centrum" to "planning center",
        "statystyk*" to "statistics",
        "ile razy" to "how many times",
        "jak często" to "how often",
        "jak czesto" to "how often",
        "raport pieśni" to "song report",
        "raport piesni" to "song report",
        "raport piosenek" to "song report",
        "użycie pieśni" to "song usage",
        "uzycie piesni" to "song usage",
        "z telefonu" to "from the phone",
        "z komórki" to "from the phone",
        "z komorki" to "from the phone",
        "przez telefon" to "from the phone",
        "na telefonie" to "on my phone",
        "podłącz telefon" to "connect my phone",
        "podlacz telefon" to "connect my phone",
        "połącz telefon" to "connect my phone",
        "polacz telefon" to "connect my phone",
        "zdalne sterowanie" to "remote control",
        "sterowanie z" to "control it from",
        "sterować z" to "control it from",
        "sterowac z" to "control it from",
        "kod qr" to "qr code",
        "kodu qr" to "qr code",
        "minut*" to "minutes",
        "ogłoś*" to "announce",
        "oglos*" to "announce",
        "poproś rodzic*" to "announce",
        "popros rodzic*" to "announce",
        "powiedz rodzic*" to "announce",
        "wezwij rodzic*" to "announce",
        "do programu" to "to the schedule",
        "w programie" to "in the schedule",
        "z programu" to "from the schedule",
        "do harmonogramu" to "to the schedule",
        "w harmonogramie" to "in the schedule",
        "wstaw" to "insert",
        "umieść" to "put",
        "umiesc" to "put",
        "następna pozycja" to "next item",
        "nastepna pozycja" to "next item",
        "następny element" to "next item",
        "nastepny element" to "next item",
        "poprzednia pozycja" to "previous item",
        "poprzedni element" to "previous item",
        "co jest na żywo" to "what's live",
        "co jest na zywo" to "what's live",
        "co jest wyświetlane" to "what is showing",
        "co jest wyswietlane" to "what is showing",
        "co teraz leci" to "what's showing",
        "czy coś jest na żywo" to "is anything live",
        "czy cos jest na zywo" to "is anything live",
        "jaka to wersja" to "what version is this",
        "jaka wersja" to "what version",
        "która wersja" to "which version",
        "ktora wersja" to "which version",
        "wersja aplikacji" to "app version",
        "wersja programu" to "app version",
        "sprawdź aktualizacj*" to "check for updates",
        "sprawdz aktualizacj*" to "check for updates",
        "czy jest aktualizacja" to "is there an update",
        "najnowsza wersja" to "latest version",
        "zaktualizuj aplikację" to "update the app",
        "zaktualizuj aplikacje" to "update the app",
        "polecenia" to "commands",
        "poleceń" to "commands",
        "polecen" to "commands",
        "komendy" to "commands",
        "komend" to "commands",
        "lista poleceń" to "list of commands",
        "lista polecen" to "list of commands",
        "lista komend" to "list of commands",
        "co mogę napisać" to "what can i type",
        "co moge napisac" to "what can i type",
        "co mogę powiedzieć" to "what can i say",
        "co moge powiedziec" to "what can i say",
        "co rozumiesz" to "what do you understand",
    ),
)
