package org.churchpresenter.helper.intent.glossary

internal val RUSSIAN = Glossary(
    "ru",
    listOf(
        // Asking where, or how.
        "где" to "where",
        "куда" to "where",
        "как мне" to "how do i",
        "как я могу" to "how can i",
        "как можно" to "how can i",
        "как" to "how do i",
        "не могу найти" to "can't find",
        "не нахожу" to "can't find",
        "покажи мне" to "show me",
        "подскажи" to "how do i",

        // Doing.
        "покажи" to "show",
        "показать" to "show",
        "покажите" to "show",
        "показывать" to "show",
        "выведи на экран" to "show",
        "выведи" to "show",
        "вывести" to "show",
        "отобрази*" to "display",
        "открой*" to "open",
        "открыть" to "open",
        "перейди на" to "go to",
        "перейди к" to "go to",
        "перейди в" to "go to",
        "перейди" to "go to",
        "перейти" to "go to",
        "переключи на" to "switch to",
        "переключись на" to "switch to",
        "найди" to "find",
        "найти" to "find",
        "прочитай" to "read",
        "сделай" to "make",
        "сделать" to "make",
        "создай" to "create",
        "создать" to "create",
        "добав*" to "add",
        "загрузи*" to "load",
        "загрузить" to "load",
        "импорт*" to "import",
        "скача*" to "download",
        "скачи*" to "download",
        "установи*" to "install",
        "выбери*" to "choose",
        "выбрать" to "choose",
        "настро*" to "set up",
        "подключ*" to "connect",
        "назнач*" to "assign",
        "убери*" to "hide",
        "убрать" to "hide",
        "скрой*" to "hide",
        "скрыть" to "hide",
        "спрячь" to "hide",
        "останови*" to "stop",
        "остановить" to "stop",
        "удали*" to "delete",
        "очисти*" to "clear",
        "очистить" to "clear",
        "затемни*" to "black out",
        "погаси экран" to "black out",
        "пустой экран" to "blank",
        "отмени*" to "undo",
        "верни как было" to "undo",
        "верни обратно" to "undo",
        "в эфир" to "go live",
        "вывести в эфир" to "go live",
        "выведи в эфир" to "go live",
        "включи*" to "turn on",
        "выключи*" to "turn off",
        "переключи*" to "toggle",
        "следующ*" to "next",
        "дальше" to "next",
        "вперед" to "forward",
        "предыдущ*" to "previous",
        "назад" to "back",
        "увелич*" to "increase",
        "больше" to "bigger",
        "крупнее" to "bigger",
        "побольше" to "bigger",
        "уменьш*" to "decrease",
        "меньше" to "smaller",
        "мельче" to "smaller",
        "поменьше" to "smaller",
        "конвертир*" to "convert",
        "конвертер*" to "converter",
        "перенес*" to "transfer",
        "перенос*" to "transfer",
        "редактир*" to "edit",
        "отредактир*" to "edit",
        "измени*" to "change",
        "поменя*" to "change",
        "переимен*" to "rename",
        "исправ*" to "fix",
        "упорядоч*" to "organize",
        "организ*" to "organize",
        "навести порядок" to "clean up",
        "сравни*" to "compare",
        "перевед*" to "translate",
        "перевести" to "translate",
        "спланир*" to "plan",
        "планир*" to "plan",
        "запланир*" to "plan",
        "автоматиз*" to "automate",
        "автоматич*" to "automatically",
        "определи*" to "identify",
        "пронумеруй*" to "number the",

        // Too small, too big, not working.
        "слишком мелк*" to "too small",
        "слишком маленьк*" to "too small",
        "плохо видно" to "hard to read",
        "не видно" to "hard to read",
        "не читается" to "hard to read",
        "трудно читать" to "hard to read",
        "слишком больш*" to "too big",
        "слишком крупн*" to "too big",
        "не помещается" to "doesn't fit",
        "не влезает" to "doesn't fit",
        "не работает" to "not working",
        "не показывает" to "not showing",
        "ничего не показывает" to "nothing shows",
        "ничего нет" to "nothing shows",
        "черный экран" to "screen is black",
        "нет сигнала" to "no signal",
        "нет картинки" to "no picture",
        "какой экран" to "which screen",
        "какой монитор" to "which monitor",
        "какой проектор" to "which projector",

        // What is on screen.
        "фон*" to "background",
        "задний план" to "backdrop",
        "текст песни" to "lyrics",
        "слова песни" to "lyrics",
        "песен" to "songs",
        "песн*" to "song",
        "гимн*" to "hymn",
        "прославлени*" to "worship",
        "библи*" to "bible",
        "писани*" to "scripture",
        "стих*" to "verse",
        "глава" to "chapter",
        "главу" to "chapter",
        "главы" to "chapter",
        "главе" to "chapter",
        "шрифт*" to "font",
        "размер*" to "size",
        "текст*" to "text",
        "слова" to "words",
        "букв*" to "letters",
        "слайд-шоу" to "slideshow",
        "слайдшоу" to "slideshow",
        "слайд*" to "slide",
        "фотограф*" to "photo",
        "фото*" to "photo",
        "картин*" to "picture",
        "изображени*" to "image",
        "альбом*" to "album",
        "презентац*" to "presentation",
        "видео" to "video",
        "фильм*" to "movie",
        "ролик*" to "clip",
        "клип*" to "clip",
        "медиа" to "media",
        "аудио" to "audio",
        "нижн* трет*" to "lower third",
        "титр*" to "lower third",
        "плашк*" to "name strap",
        "имя и должность" to "name and title",
        "объявлени*" to "announcement",
        "анонс*" to "announcement",
        "бегущ* строк*" to "ticker",
        "детск* комнат*" to "kids room",
        "обратн* отсчет*" to "countdown",
        "отсчет*" to "countdown",
        "таймер*" to "timer",
        "секундомер*" to "stopwatch",
        "часы" to "clock",
        "текущее время" to "current time",
        "время" to "time",
        "заметк*" to "notes",
        "аккорд*" to "chord",
        "перевод*" to "translation",
        "язык*" to "language",
        "двуязычн*" to "bilingual",
        "на другом языке" to "another language",
        "другой язык" to "another language",
        "второй язык" to "second language",
        "на двух языках" to "two languages",

        // Screens and outputs.
        "главн* экран*" to "main screen",
        "полный экран" to "full screen",
        "на весь экран" to "full screen",
        "полноэкранн*" to "fullscreen",
        "второй экран" to "second screen",
        "экран*" to "screen",
        "проектор*" to "projector",
        "монитор* на сцене" to "stage monitor",
        "монитор* для сцены" to "stage monitor",
        "сценическ* монитор*" to "stage monitor",
        "суфлер*" to "confidence monitor",
        "монитор*" to "monitor",
        "дисплей*" to "display",
        "вывод*" to "output",
        "окно вывода" to "output window",
        "сцен*" to "stage",
        "зон*" to "zone",
        "раскладк*" to "layout",
        "макет*" to "layout",
        "расположени*" to "arrangement",
        "сообщени*" to "message",
        "отправ*" to "send",
        "предпросмотр*" to "preview",
        "превью" to "preview",
        "что на экране" to "what is on screen",
        "профил*" to "profile",
        "трансляци*" to "stream",
        "стрим*" to "stream",
        "телевизор*" to "tv",

        // Pages, tabs and tools.
        "настройк*" to "settings",
        "параметр*" to "options",
        "мастер настройки" to "setup wizard",
        "начать сначала" to "start over",
        "сочетани* клавиш" to "shortcut",
        "горяч* клавиш*" to "hotkeys",
        "клавиатур*" to "keyboard",
        "вкладк*" to "tab",
        "библиотек* песен" to "song library",
        "библиотек*" to "library",
        "веб" to "web",
        "сайт*" to "website",
        "браузер*" to "browser",
        "словар*" to "dictionary",
        "стронг*" to "strong",
        "камер*" to "camera",
        "холст*" to "canvas",
        "сервер*" to "server",
        "удаленн*" to "remote",
        "пульт*" to "remote",
        "телефон*" to "phone",
        "планшет*" to "tablet",
        "компаньон*" to "companion",
        "интеграци*" to "integrations",

        // Services and planning.
        "порядок служения" to "order of service",
        "программа служения" to "order of service",
        "богослужени*" to "service",
        "служени*" to "service",
        "собрани*" to "meeting",
        "воскресень*" to "sunday",
        "календар*" to "calendar",
        "расписани*" to "schedule",
        "плейлист*" to "playlist",
        "каждое воскресенье" to "every sunday",
        "каждую неделю" to "every week",
        "еженедельн*" to "weekly",
        "ежемесячн*" to "monthly",
        "повторя*" to "repeat",
        "шаблон*" to "template",

        // Many, all, both.
        "все" to "all",
        "всё" to "all",
        "везде" to "everything",
        "оба" to "both",
        "обоих" to "both",
        "несколько" to "several",
        "много" to "many",
        "сразу" to "at once",
        "для этого служения" to "this service",
        "на сегодня" to "for today",
        "временно" to "temporarily",

        // Languages, by name.
        "русск*" to "russian",
        "украинск*" to "ukrainian",
        "белорус*" to "belarusian",
        "английск*" to "english",
        "испанск*" to "spanish",
        "немецк*" to "german",
        "французск*" to "french",
        "польск*" to "polish",
        "казахск*" to "kazakh",
        "румынск*" to "romanian",
        "молдавск*" to "moldovan",

        // Colors.
        "темно-син*" to "navy",
        "светло-син*" to "light blue",
        "голуб*" to "light blue",
        "синий" to "blue",
        "синим" to "blue",
        "синего" to "blue",
        "синей" to "blue",
        "синюю" to "blue",
        "синее" to "blue",
        "черн*" to "black",
        "белый" to "white",
        "белым" to "white",
        "белого" to "white",
        "белой" to "white",
        "белую" to "white",
        "серый" to "grey",
        "серым" to "grey",
        "серого" to "grey",
        "серой" to "grey",
        "серебрист*" to "silver",
        "красн*" to "red",
        "бордов*" to "maroon",
        "оранжев*" to "orange",
        "желт*" to "yellow",
        "золот*" to "gold",
        "зелен*" to "green",
        "салатов*" to "lime",
        "бирюзов*" to "turquoise",
        "фиолетов*" to "purple",
        "лилов*" to "violet",
        "розов*" to "pink",
        "коричнев*" to "brown",
        "бежев*" to "beige",
        "кремов*" to "cream",
        "темн*" to "dark",
        "светл*" to "light",

        // Talking to the helper.
        "привет" to "hello",
        "здравствуй*" to "hello",
        "добрый день" to "hello",
        "помоги*" to "help",
        "помощь" to "help",
        "что ты умеешь" to "what can you do",
        "что ты можешь" to "what can you do",
        "кто ты" to "who are you",
        "спасибо" to "thanks",
        "благодарю" to "thank you",
        "пожалуйста" to "please",
        "уик" to "wick",
        "вик" to "wick",

        // Newer requests.
        "искать" to "search",
        "ищи" to "search",
        "ищу" to "search",
        "поищи" to "search",
        "поиск*" to "search",
        "найти песн*" to "find a song",
        "найди песн*" to "find the song",
        "найти стих*" to "find a verse",
        "найди стих*" to "find the verse",
        "номер песни" to "song number",
        "по номеру" to "by number",
        "по названию" to "by title",
        "номер" to "number",
        "под названием" to "called",
        "называется" to "called",
        "избранн*" to "favorite",
        "любим*" to "favorite",
        "эт* песн*" to "this song",
        "кажд* песн*" to "each song",
        "сво* фон*" to "own background",
        "собственн* фон*" to "own background",
        "отдельн* фон*" to "own background",
        "нескольк* стих*" to "several verses",
        "много стихов" to "many verses",
        "больше одного стиха" to "more than one verse",
        "диапазон* стих*" to "verse range",
        "отрывок" to "a passage",
        "отрывка" to "a passage",
        "еще одн*" to "another",
        "истори*" to "history",
        "что мы только что показ*" to "what did we just show",
        "что только что показ*" to "what did we just show",
        "что мы показ*" to "what did we show",
        "недавн* стих*" to "recent verses",
        "перекрестн* ссылк*" to "cross references",
        "связанн* стих*" to "related verses",
        "связанн* мест*" to "related passages",
        "параллельн* мест*" to "parallel passages",
        "похож* стих*" to "similar verses",
        "веб-сайт*" to "website",
        "вебсайт*" to "website",
        "веб-страниц*" to "web page",
        "интернет-страниц*" to "internet page",
        "страниц* в интернете" to "internet page",
        "планнинг центр*" to "planning center",
        "планинг центр*" to "planning center",
        "статистик*" to "statistics",
        "сколько раз" to "how many times",
        "как часто" to "how often",
        "отчет* по песн*" to "song report",
        "использовани* песен" to "song usage",
        "с телефона" to "from my phone",
        "с моего телефона" to "from my phone",
        "с планшета" to "from my tablet",
        "на телефоне" to "on my phone",
        "подключ* телефон*" to "connect my phone",
        "дистанционн* управлени*" to "remote control",
        "удаленн* управлени*" to "remote control",
        "qr-код*" to "qr code",
        "qr код*" to "qr code",
        "минут*" to "minutes",
        "мин" to "min",
        "объявление:" to "announce",
        "объяви:" to "announce",
        "объяви" to "announce",
        "попроси родителей" to "announce",
        "попросите родителей" to "announce",
        "поставь" to "put",
        "в программу" to "to the schedule",
        "в программе" to "in the schedule",
        "из программы" to "from the schedule",
        "в расписание" to "to the schedule",
        "в расписании" to "in the schedule",
        "пункт*" to "item",
        "что сейчас в эфире" to "what's live",
        "что в эфире" to "what's live",
        "что сейчас на экране" to "what is on screen",
        "что сейчас показывается" to "what's showing",
        "что показывается" to "what's showing",
        "что-нибудь в эфире" to "is anything live",
        "что-то в эфире" to "is anything live",
        "какая это версия" to "what version is this",
        "как* верси*" to "what version",
        "верси* программ*" to "app version",
        "верси* приложени*" to "app version",
        "последн* верси*" to "latest version",
        "провер* обновлени*" to "check for updates",
        "есть ли обновлени*" to "is there an update",
        "верси*" to "version",
        "список команд" to "list of commands",
        "какие команды" to "commands",
        "все команды" to "all commands",
        "покажи команды" to "show commands",
        "что я могу сказать" to "what can i say",
        "что можно сказать" to "what can i say",
        "что я могу написать" to "what can i type",
        "что можно написать" to "what can i type",
        "что ты понимаешь" to "what do you understand",
        "на сейчас" to "for now",
        "пока что" to "for now",
        "разом" to "together",

        // Look requests.
        "изменить текст песни" to "change song lyrics",
        "измени текст песни" to "change song lyrics",
        "опечатк*" to "typo",
        "ошибк* в тексте" to "mistake in the lyrics",
        "маркер* конца песни" to "end of song marker",
        "знак* конца песни" to "end of song marker",
        "метк* конца песни" to "end of song marker",
        "конец песни" to "end of song",
        "конца песни" to "end of song",
        "в конце песни" to "end of the song",
        "жирн*" to "bold",
        "полужирн*" to "bold",
        "курсив*" to "italic",
        "подчеркн*" to "underline",
        "подчеркив*" to "underline",
        "обводк*" to "outline",
        "контур*" to "outline",
        "тень" to "shadow",
        "тени" to "shadow",
        "тенью" to "shadow",
        "поля" to "margins",
        "полей" to "margins",
        "отступ*" to "margins",
        "края" to "edges",
        "краев" to "edges",
        "наверх" to "to the top",
        "вверх" to "to the top",
        "наверху" to "top",
        "вверху" to "top",
        "сверху" to "top",
        "вниз" to "to the bottom",
        "внизу" to "bottom",
        "снизу" to "bottom",
        "посередине" to "middle",
        "по центру" to "center",
        "в центр" to "center",
        "слева" to "left",
        "влево" to "left",
        "справа" to "right",
        "вправо" to "right",
        "выравнивани*" to "alignment",
        "выровня*" to "align",
        "положени*" to "position",
        "позици*" to "position",
        "перемест*" to "move",
        "передвин*" to "move",
        "сдвин*" to "move",
        "гарнитур*" to "typeface",
        "внешн* вид*" to "appearance",
        "вид" to "look",
        "выгляд*" to "look",
        "стил*" to "style",
        "оформ*" to "style",
        "цвет*" to "color",
        "название песни" to "song title",
        "названия песни" to "song title",
        "названи*" to "title",
        "заголов*" to "title",
        "ссылк*" to "reference",
    ),
)
