#!/usr/bin/env python3

import xml.etree.ElementTree as ET
import sys
import os
import glob

BOOK_NAMES = {
    1: "Genesis",
    2: "Exodus",
    3: "Leviticus",
    4: "Numbers",
    5: "Deuteronomy",
    6: "Joshua",
    7: "Judges",
    8: "Ruth",
    9: "1 Samuel",
    10: "2 Samuel",
    11: "1 Kings",
    12: "2 Kings",
    13: "1 Chronicles",
    14: "2 Chronicles",
    15: "Ezra",
    16: "Nehemiah",
    17: "Esther",
    18: "Job",
    19: "Psalms",
    20: "Proverbs",
    21: "Ecclesiastes",
    22: "Song of Solomon",
    23: "Isaiah",
    24: "Jeremiah",
    25: "Lamentations",
    26: "Ezekiel",
    27: "Daniel",
    28: "Hosea",
    29: "Joel",
    30: "Amos",
    31: "Obadiah",
    32: "Jonah",
    33: "Micah",
    34: "Nahum",
    35: "Habakkuk",
    36: "Zephaniah",
    37: "Haggai",
    38: "Zechariah",
    39: "Malachi",
    40: "Matthew",
    41: "Mark",
    42: "Luke",
    43: "John",
    44: "Acts",
    45: "Romans",
    46: "1 Corinthians",
    47: "2 Corinthians",
    48: "Galatians",
    49: "Ephesians",
    50: "Philippians",
    51: "Colossians",
    52: "1 Thessalonians",
    53: "2 Thessalonians",
    54: "1 Timothy",
    55: "2 Timothy",
    56: "Titus",
    57: "Philemon",
    58: "Hebrews",
    59: "James",
    60: "1 Peter",
    61: "2 Peter",
    62: "1 John",
    63: "2 John",
    64: "3 John",
    65: "Jude",
    66: "Revelation",
}

UKRAINIAN_BOOK_NAMES = {
    1: "Буття",
    2: "Вихід",
    3: "Левит",
    4: "Числа",
    5: "Повторний Закон",
    6: "Ісус Навин",
    7: "Книга Суддів",
    8: "Рут",
    9: "1-а Царств",
    10: "2-а Царств",
    11: "3-я Царств",
    12: "4-а Царств",
    13: "1-а Паралипоменон",
    14: "2-а Паралипоменон",
    15: "Ездра",
    16: "Неемія",
    17: "Естер",
    18: "Йов",
    19: "Псалтир",
    20: "Приповістей",
    21: "Екклесіаст",
    22: "Пісня Пісень",
    23: "Ісая",
    24: "Єремія",
    25: "Плач Єремії",
    26: "Єзекііль",
    27: "Даниїл",
    28: "Ося",
    29: "Йоель",
    30: "Амос",
    31: "Авдій",
    32: "Йона",
    33: "Михей",
    34: "Наум",
    35: "Аввакум",
    36: "Софонія",
    37: "Аггей",
    38: "Захарія",
    39: "Малахія",
    40: "Від Матвія",
    41: "Від Марка",
    42: "Від Луки",
    43: "Від Івана",
    44: "Діяння",
    45: "До Римлян",
    46: "1-е до Коринтян",
    47: "2-е до Коринтян",
    48: "До Галатів",
    49: "До Ефесян",
    50: "До Филип'ян",
    51: "До Колосян",
    52: "1-е до Солунян",
    53: "2-е до Солунян",
    54: "1-е до Тимофія",
    55: "2-е до Тимофія",
    56: "До Тита",
    57: "До Филимона",
    58: "До Євреїв",
    59: "Якова",
    60: "1-е Петра",
    61: "2-е Петра",
    62: "1-е Івана",
    63: "2-е Івана",
    64: "3-е Івана",
    65: "Юди",
    66: "Об'явлення",
}

RUSSIAN_BOOK_NAMES = {
    1: "Бытие",
    2: "Исход",
    3: "Левит",
    4: "Числа",
    5: "Второзаконие",
    6: "Иисус Навин",
    7: "Книга Судей",
    8: "Руфь",
    9: "1-я Царств",
    10: "2-я Царств",
    11: "3-я Царств",
    12: "4-я Царств",
    13: "1-я Паралипоменон",
    14: "2-я Паралипоменон",
    15: "Ездра",
    16: "Неемия",
    17: "Есфирь",
    18: "Иов",
    19: "Псалтирь",
    20: "Притчи",
    21: "Екклесиаст",
    22: "Песни Песней",
    23: "Исаия",
    24: "Иеремия",
    25: "Плач Иеремии",
    26: "Иезекииль",
    27: "Даниил",
    28: "Осия",
    29: "Иоиль",
    30: "Амос",
    31: "Авдий",
    32: "Иона",
    33: "Михей",
    34: "Наум",
    35: "Аввакум",
    36: "Софония",
    37: "Аггей",
    38: "Захария",
    39: "Малахия",
    40: "От Матфея",
    41: "От Марка",
    42: "От Луки",
    43: "От Иоанна",
    44: "Деяния",
    45: "К Римлянам",
    46: "1-е Коринфянам",
    47: "2-е Коринфянам",
    48: "К Галатам",
    49: "К Ефесянам",
    50: "К Филиппийцам",
    51: "К Колоссянам",
    52: "1-е Фессалоникийцам",
    53: "2-е Фессалоникийцам",
    54: "1-е Тимофею",
    55: "2-е Тимофею",
    56: "К Титу",
    57: "К Филимону",
    58: "К Евреям",
    59: "Иакова",
    60: "1-е Петра",
    61: "2-е Петра",
    62: "1-е Иоанна",
    63: "2-е Иоанна",
    64: "3-е Иоанна",
    65: "Иуды",
    66: "Откровение",
}

GERMAN_BOOK_NAMES = {
    1: "1. Mose",
    2: "2. Mose",
    3: "3. Mose",
    4: "4. Mose",
    5: "5. Mose",
    6: "Josua",
    7: "Richter",
    8: "Ruth",
    9: "1. Samuel",
    10: "2. Samuel",
    11: "1. Könige",
    12: "2. Könige",
    13: "1. Chronika",
    14: "2. Chronika",
    15: "Esra",
    16: "Nehemia",
    17: "Esther",
    18: "Hiob",
    19: "Psalm",
    20: "Sprüche",
    21: "Prediger",
    22: "Hohelied",
    23: "Jesaja",
    24: "Jeremia",
    25: "Klagelieder",
    26: "Hesekiel",
    27: "Daniel",
    28: "Hosea",
    29: "Joel",
    30: "Amos",
    31: "Obadja",
    32: "Jona",
    33: "Micha",
    34: "Nahum",
    35: "Habakuk",
    36: "Zephanja",
    37: "Haggai",
    38: "Sacharja",
    39: "Maleachi",
    40: "Matthäus",
    41: "Markus",
    42: "Lukas",
    43: "Johannes",
    44: "Apostelgeschichte",
    45: "Römer",
    46: "1. Korinther",
    47: "2. Korinther",
    48: "Galater",
    49: "Epheser",
    50: "Philipper",
    51: "Kolosser",
    52: "1. Thessalonicher",
    53: "2. Thessalonicher",
    54: "1. Timotheus",
    55: "2. Timotheus",
    56: "Titus",
    57: "Philemon",
    58: "Hebräer",
    59: "Jakobus",
    60: "1. Petrus",
    61: "2. Petrus",
    62: "1. Johannes",
    63: "2. Johannes",
    64: "3. Johannes",
    65: "Judas",
    66: "Offenbarung",
}

FRENCH_BOOK_NAMES = {
    1: "Genèse",
    2: "Exode",
    3: "Lévitique",
    4: "Nombres",
    5: "Deutéronome",
    6: "Josué",
    7: "Juges",
    8: "Ruth",
    9: "1 Samuel",
    10: "2 Samuel",
    11: "1 Rois",
    12: "2 Rois",
    13: "1 Chroniques",
    14: "2 Chroniques",
    15: "Esdras",
    16: "Néhémie",
    17: "Esther",
    18: "Job",
    19: "Psaumes",
    20: "Proverbes",
    21: "Ecclésiaste",
    22: "Cantique des cantiques",
    23: "Ésaïe",
    24: "Jérémie",
    25: "Lamentations",
    26: "Ézéchiel",
    27: "Daniel",
    28: "Osée",
    29: "Joël",
    30: "Amos",
    31: "Abdias",
    32: "Jonas",
    33: "Michée",
    34: "Nahum",
    35: "Habacuc",
    36: "Sophonie",
    37: "Aggée",
    38: "Zacharie",
    39: "Malachie",
    40: "Matthieu",
    41: "Marc",
    42: "Luc",
    43: "Jean",
    44: "Actes",
    45: "Romains",
    46: "1 Corinthiens",
    47: "2 Corinthiens",
    48: "Galates",
    49: "Éphésiens",
    50: "Philippiens",
    51: "Colossiens",
    52: "1 Thessaloniciens",
    53: "2 Thessaloniciens",
    54: "1 Timothée",
    55: "2 Timothée",
    56: "Tite",
    57: "Philémon",
    58: "Hébreux",
    59: "Jacques",
    60: "1 Pierre",
    61: "2 Pierre",
    62: "1 Jean",
    63: "2 Jean",
    64: "3 Jean",
    65: "Jude",
    66: "Apocalypse",
}

SPANISH_BOOK_NAMES = {
    1: "Génesis",
    2: "Éxodo",
    3: "Levítico",
    4: "Números",
    5: "Deuteronomio",
    6: "Josué",
    7: "Jueces",
    8: "Ruth",
    9: "1 Samuel",
    10: "2 Samuel",
    11: "1 Reyes",
    12: "2 Reyes",
    13: "1 Crónicas",
    14: "2 Crónicas",
    15: "Esdras",
    16: "Nehemías",
    17: "Ester",
    18: "Job",
    19: "Salmos",
    20: "Proverbios",
    21: "Eclesiastés",
    22: "Cantar de los cantares",
    23: "Isaías",
    24: "Jeremías",
    25: "Lamentaciones",
    26: "Ezequiel",
    27: "Daniel",
    28: "Oseas",
    29: "Joel",
    30: "Amós",
    31: "Abdías",
    32: "Jonás",
    33: "Miqueas",
    34: "Nahum",
    35: "Habacuc",
    36: "Sofonías",
    37: "Hageo",
    38: "Zacarías",
    39: "Malaquías",
    40: "Mateo",
    41: "Marcos",
    42: "Lucas",
    43: "Juan",
    44: "Hechos",
    45: "Romanos",
    46: "1 Corintios",
    47: "2 Corintios",
    48: "Gálatas",
    49: "Efesios",
    50: "Filipenses",
    51: "Colosenses",
    52: "1 Tesalonicenses",
    53: "2 Tesalonicenses",
    54: "1 Timoteo",
    55: "2 Timoteo",
    56: "Tito",
    57: "Filemón",
    58: "Hebreos",
    59: "Santiago",
    60: "1 Pedro",
    61: "2 Pedro",
    62: "1 Juan",
    63: "2 Juan",
    64: "3 Juan",
    65: "Judas",
    66: "Apocalipsis",
}

PORTUGUESE_BOOK_NAMES = {
    1: "Gênesis",
    2: "Êxodo",
    3: "Levítico",
    4: "Números",
    5: "Deuteronômio",
    6: "Josué",
    7: "Juízes",
    8: "Rute",
    9: "1 Samuel",
    10: "2 Samuel",
    11: "1 Reis",
    12: "2 Reis",
    13: "1 Crônicas",
    14: "2 Crônicas",
    15: "Esdras",
    16: "Neemias",
    17: "Ester",
    18: "Jó",
    19: "Salmos",
    20: "Provérbios",
    21: "Eclesiastes",
    22: "Cântico dos Cânticos",
    23: "Isaías",
    24: "Jeremias",
    25: "Lamentações",
    26: "Ezequiel",
    27: "Daniel",
    28: "Oséias",
    29: "Joel",
    30: "Amós",
    31: "Obadias",
    32: "Jonás",
    33: "Miquéias",
    34: "Naum",
    35: "Habacuque",
    36: "Sofonias",
    37: "Ageu",
    38: "Zacarias",
    39: "Malaquias",
    40: "Mateus",
    41: "Marcos",
    42: "Lucas",
    43: "João",
    44: "Atos",
    45: "Romanos",
    46: "1 Coríntios",
    47: "2 Coríntios",
    48: "Gálatas",
    49: "Efésios",
    50: "Filipenses",
    51: "Colossenses",
    52: "1 Tessalonicenses",
    53: "2 Tessalonicenses",
    54: "1 Timóteo",
    55: "2 Timóteo",
    56: "Tito",
    57: "Filemón",
    58: "Hebreus",
    59: "Tiago",
    60: "1 Pedro",
    61: "2 Pedro",
    62: "1 João",
    63: "2 João",
    64: "3 João",
    65: "Judas",
    66: "Apocalipse",
}

ITALIAN_BOOK_NAMES = {
    1: "Genesi",
    2: "Esodo",
    3: "Levitico",
    4: "Numeri",
    5: "Deuteronomio",
    6: "Giosuè",
    7: "Giudici",
    8: "Rut",
    9: "1 Samuele",
    10: "2 Samuele",
    11: "1 Re",
    12: "2 Re",
    13: "1 Cronache",
    14: "2 Cronache",
    15: "Esdra",
    16: "Neemia",
    17: "Ester",
    18: "Giobbe",
    19: "Salmi",
    20: "Proverbi",
    21: "Ecclesiaste",
    22: "Cantico dei cantici",
    23: "Isaia",
    24: "Geremia",
    25: "Lamentazioni",
    26: "Ezechiele",
    27: "Daniele",
    28: "Osea",
    29: "Gioele",
    30: "Amos",
    31: "Abdìa",
    32: "Giona",
    33: "Michea",
    34: "Naum",
    35: "Abacuc",
    36: "Sofonia",
    37: "Aggeo",
    38: "Zaccaria",
    39: "Malachia",
    40: "Matteo",
    41: "Marco",
    42: "Luca",
    43: "Giovanni",
    44: "Atti",
    45: "Romani",
    46: "1 Corinzi",
    47: "2 Corinzi",
    48: "Galati",
    49: "Efesini",
    50: "Filippesi",
    51: "Colossesi",
    52: "1 Tessalonicenses",
    53: "2 Tessalonicenses",
    54: "1 Timoteo",
    55: "2 Timoteo",
    56: "Tito",
    57: "Filemone",
    58: "Ebrei",
    59: "Giacomo",
    60: "1 Pietro",
    61: "2 Pietro",
    62: "1 Giovanni",
    63: "2 Giovanni",
    64: "3 Giovanni",
    65: "Giuda",
    66: "Apocalisse",
}

DANISH_BOOK_NAMES = {
    1: "1 Mosebog",
    2: "2 Mosebog",
    3: "3 Mosebog",
    4: "4 Mosebog",
    5: "5 Mosebog",
    6: "Josua",
    7: "Dommerbogen",
    8: "Rut",
    9: "1 Samuelisbog",
    10: "2 Samuelisbog",
    11: "1 Kongebog",
    12: "2 Kongebog",
    13: "1 Krønikebog",
    14: "2 Krønikebog",
    15: "Esra",
    16: "Nehemias",
    17: "Ester",
    18: "Job",
    19: "Salmerne",
    20: "Ordsprogene",
    21: "Prædikerens Bog",
    22: "Højsangen",
    23: "Esajas",
    24: "Jeremias",
    25: "Klagesangene",
    26: "Ezekiels Bog",
    27: "Daniels Bog",
    28: "Hoseas",
    29: "Joel",
    30: "Amos",
    31: "Obadjas",
    32: "Jonas",
    33: "Mika",
    34: "Nahum",
    35: "Habakuk",
    36: "Sefanias",
    37: "Haggaj",
    38: "Zakarias",
    39: "Malaki",
    40: "Matthæus",
    41: "Markus",
    42: "Lukas",
    43: "Johannes",
    44: "Apostlenes Gerninger",
    45: "Romerbrevet",
    46: "1 Korintherbrev",
    47: "2 Korintherbrev",
    48: "Galaterbrevet",
    49: "Efeserbrevet",
    50: "Filipperbrevet",
    51: "Kolosserbrevet",
    52: "1 Thessalonikerbrev",
    53: "2 Thessalonikerbrev",
    54: "1 Timotheusbrev",
    55: "2 Timotheusbrev",
    56: "Titusbrevet",
    57: "Filemonbrevet",
    58: "Hebræerbrevet",
    59: "Jakobs Brev",
    60: "1 Peters Brev",
    61: "2 Peters Brev",
    62: "1 Johannes Brev",
    63: "2 Johannes Brev",
    64: "3 Johannes Brev",
    65: "Judas's Brev",
    66: "Aabenbaring",
}

SWEDISH_BOOK_NAMES = {
    1: "1 Mosebok",
    2: "2 Mosebok",
    3: "3 Mosebok",
    4: "4 Mosebok",
    5: "5 Mosebok",
    6: "Josua",
    7: "Domarboken",
    8: "Rut",
    9: "1 Samuelsboken",
    10: "2 Samuelsboken",
    11: "1 Kungaboken",
    12: "2 Kungaboken",
    13: "1 Krönikeboken",
    14: "2 Krönikeboken",
    15: "Esra",
    16: "Nehemia",
    17: "Ester",
    18: "Job",
    19: "Psaltaren",
    20: "Ordspråken",
    21: "Predikaren",
    22: "Höga visan",
    23: "Jesaja",
    24: "Jeremia",
    25: "Klagovisorna",
    26: "Hesekiel",
    27: "Daniel",
    28: "Hosea",
    29: "Joel",
    30: "Amos",
    31: "Obadja",
    32: "Jona",
    33: "Mika",
    34: "Nahum",
    35: "Habakuk",
    36: "Sefanja",
    37: "Haggai",
    38: "Sakarja",
    39: "Malaki",
    40: "Matteus",
    41: "Markus",
    42: "Lukas",
    43: "Johannes",
    44: "Apostlagärningarna",
    45: "Romarbrevet",
    46: "1 Korintierbrevet",
    47: "2 Korintierbrevet",
    48: "Galaterbrevet",
    49: "Efesierbrevet",
    50: "Filipperbrevet",
    51: "Kolosserbrevet",
    52: "1 Tessalonikerbrevet",
    53: "2 Tessalonikerbrevet",
    54: "1 Timotheusbrevet",
    55: "2 Timotheusbrevet",
    56: "Titusbrevet",
    57: "Filemonbrevet",
    58: "Hebreerbrevet",
    59: "Jakobs brev",
    60: "1 Petrusbrev",
    61: "2 Petrusbrev",
    62: "1 Johannesbrev",
    63: "2 Johannesbrev",
    64: "3 Johannesbrev",
    65: "Judas brev",
    66: "Uppenbarelseboken",
}

NORWEGIAN_BOOK_NAMES = {
    1: "1 Mosebok",
    2: "2 Mosebok",
    3: "3 Mosebok",
    4: "4 Mosebok",
    5: "5 Mosebok",
    6: "Josva",
    7: "Dommerboka",
    8: "Rut",
    9: "1 Samuelsboka",
    10: "2 Samuelsboka",
    11: "1 Kongeboka",
    12: "2 Kongeboka",
    13: "1 Krønikebok",
    14: "2 Krønikebok",
    15: "Esra",
    16: "Nehemia",
    17: "Ester",
    18: "Job",
    19: "Salme",
    20: "Ordspråka",
    21: "Predikaren",
    22: "Høysangen",
    23: "Jesaja",
    24: "Jeremia",
    25: "Klagesangene",
    26: "Esekiel",
    27: "Daniel",
    28: "Hosea",
    29: "Joel",
    30: "Amos",
    31: "Obadja",
    32: "Jona",
    33: "Mika",
    34: "Nahum",
    35: "Habakkuk",
    36: "Sefanias",
    37: "Haggai",
    38: "Sakarja",
    39: "Malaki",
    40: "Matteus",
    41: "Markus",
    42: "Lukas",
    43: "Johannes",
    44: "Apostlenes gjerninger",
    45: "Romerbrevet",
    46: "1 Korinterbrev",
    47: "2 Korinterbrev",
    48: "Galaterbrevet",
    49: "Efesierbrevet",
    50: "Filipperbrevet",
    51: "Kolosserbrevet",
    52: "1 Tessalonikerbrev",
    53: "2 Tessalonikerbrev",
    54: "1 Timoteusbrev",
    55: "2 Timoteusbrev",
    56: "Titusbrevet",
    57: "Filemonbrevet",
    58: "Hebreerbrevet",
    59: "Jakobs brev",
    60: "1 Peters brev",
    61: "2 Peters brev",
    62: "1 Johannes brev",
    63: "2 Johannes brev",
    64: "3 Johannes brev",
    65: "Judas brev",
    66: "Åpenbaringen",
}

DUTCH_BOOK_NAMES = {
    1: "Genesis",
    2: "Exodus",
    3: "Leviticus",
    4: "Numeri",
    5: "Deuteronomium",
    6: "Jozua",
    7: "Richteren",
    8: "Ruth",
    9: "1 Samuel",
    10: "2 Samuel",
    11: "1 Koningen",
    12: "2 Koningen",
    13: "1 Kronieken",
    14: "2 Kronieken",
    15: "Ezra",
    16: "Nehemia",
    17: "Ester",
    18: "Job",
    19: "Psalmen",
    20: "Spreuken",
    21: "Prediker",
    22: "Hooglied",
    23: "Jesaja",
    24: "Jeremia",
    25: "Klaagliederen",
    26: "Ezechiel",
    27: "Daniel",
    28: "Hosea",
    29: "Joël",
    30: "Amos",
    31: "Obadja",
    32: "Jona",
    33: "Micha",
    34: "Nahum",
    35: "Habakuk",
    36: "Zefanja",
    37: "Haggai",
    38: "Zacharia",
    39: "Maleachi",
    40: "Matteüs",
    41: "Marcus",
    42: "Lucas",
    43: "Johannes",
    44: "Handelingen",
    45: "Romeinen",
    46: "1 Korintiërs",
    47: "2 Korintiërs",
    48: "Galaten",
    49: "Efeziërs",
    50: "Filippenzen",
    51: "Kolossenzen",
    52: "1 Tessalonicenzen",
    53: "2 Tessalonicenzen",
    54: "1 Timoteus",
    55: "2 Timoteus",
    56: "Titus",
    57: "Filemon",
    58: "Hebreeën",
    59: "Jakobus",
    60: "1 Petrus",
    61: "2 Petrus",
    62: "1 Johannes",
    63: "2 Johannes",
    64: "3 Johannes",
    65: "Judas",
    66: "Openbaring",
}

FINNISH_BOOK_NAMES = {
    1: "1. Mooseksen kirja",
    2: "2. Mooseksen kirja",
    3: "3. Mooseksen kirja",
    4: "4. Mooseksen kirja",
    5: "5. Mooseksen kirja",
    6: "Joosua",
    7: "Tuomarit",
    8: "Ruut",
    9: "1. Samuelin kirja",
    10: "2. Samuelin kirja",
    11: "1. Kuninkaiden kirja",
    12: "2. Kuninkaiden kirja",
    13: "1. Aikakirja",
    14: "2. Aikakirja",
    15: "Esra",
    16: "Nehemia",
    17: "Ester",
    18: "Job",
    19: "Psalmit",
    20: "Sananlaskut",
    21: "Saarnaaja",
    22: "Lauluja",
    23: "Jesaja",
    24: "Jeremia",
    25: "Valitukset",
    26: "Hesekiel",
    27: "Daniel",
    28: "Hoosea",
    29: "Joel",
    30: "Aamoksen",
    31: "Obadja",
    32: "Jona",
    33: "Mika",
    34: "Nahum",
    35: "Habakuk",
    36: "Sefanja",
    37: "Haggai",
    38: "Sakarja",
    39: "Malakia",
    40: "Matteus",
    41: "Markus",
    42: "Luukas",
    43: "Johannes",
    44: "Apostolien teot",
    45: "Roomalaisille",
    46: "1. Korinttolaisille",
    47: "2. Korinttolaisille",
    48: "Galatalaisille",
    49: "Efesolaisille",
    50: "Filippiläisille",
    51: "Kolossalaisille",
    52: "1. Tessalonikalaisille",
    53: "2. Tessalonikalaisille",
    54: "1. Timoteukselle",
    55: "2. Timoteukselle",
    56: "Titukselle",
    57: "Filemonille",
    58: "Hebrealaisille",
    59: "Jaakob",
    60: "1. Pietari",
    61: "2. Pietari",
    62: "1. Johannes",
    63: "2. Johannes",
    64: "3. Johannes",
    65: "Juudas",
    66: "Ilmestys",
}

POLISH_BOOK_NAMES = {
    1: "Księga Rodzaju",
    2: "Księga Wyjścia",
    3: "Księga Kapłańska",
    4: "Księga Liczb",
    5: "Księga Powtórzonego Prawa",
    6: "Księga Jozuego",
    7: "Księga Sędziów",
    8: "Księga Rut",
    9: "1 Księga Samuela",
    10: "2 Księga Samuela",
    11: "1 Księga Królewska",
    12: "2 Księga Królewska",
    13: "1 Księga Kronik",
    14: "2 Księga Kronik",
    15: "Księga Ezdrasza",
    16: "Księga Nehemiasza",
    17: "Księga Estery",
    18: "Księga Hioba",
    19: "Księga Psalmów",
    20: "Księga Przysłów",
    21: "Księga Koheleta",
    22: "Pieśń nad Pieśniami",
    23: "Księga Izajasza",
    24: "Księga Jeremiasza",
    25: "Treny",
    26: "Księga Ezechiela",
    27: "Księga Daniela",
    28: "Księga Ozeasza",
    29: "Księga Joela",
    30: "Księga Amosa",
    31: "Księga Abdiasza",
    32: "Księga Jonasza",
    33: "Księga Micheasza",
    34: "Księga Nahuma",
    35: "Księga Habakuka",
    36: "Księga Sofoniasza",
    37: "Księga Aggeusza",
    38: "Księga Zachariasza",
    39: "Księga Malachiasza",
    40: "Ewangelia według świętego Mateusza",
    41: "Ewangelia według świętego Marka",
    42: "Ewangelia według świętego Łukasza",
    43: "Ewangelia według świętego Jana",
    44: "Dzieje Apostolskie",
    45: "List do Rzymian",
    46: "1 List do Koryntian",
    47: "2 List do Koryntian",
    48: "List do Galatów",
    49: "List do Efezjan",
    50: "List do Filipian",
    51: "List do Kolosan",
    52: "1 List do Tesaloniczan",
    53: "2 List do Tesaloniczan",
    54: "1 List do Tymoteusza",
    55: "2 List do Tymoteusza",
    56: "List do Tytusa",
    57: "List do Filemona",
    58: "List do Hebrajczyków",
    59: "List świętego Jakuba",
    60: "1 List świętego Piotra",
    61: "2 List świętego Piotra",
    62: "1 List świętego Jana",
    63: "2 List świętego Jana",
    64: "3 List świętego Jana",
    65: "List Judy",
    66: "Księga Apokalipsy",
}

HUNGARIAN_BOOK_NAMES = {
    1: "Mózes első könyve",
    2: "Mózes második könyve",
    3: "Mózes harmadik könyve",
    4: "Mózes negyedik könyve",
    5: "Mózes ötödik könyve",
    6: "Józsué könyve",
    7: "Bírák könyve",
    8: "Ruth könyve",
    9: "Sámuel első könyve",
    10: "Sámuel második könyve",
    11: "Királyok első könyve",
    12: "Királyok második könyve",
    13: "Krónikák első könyve",
    14: "Krónikák második könyve",
    15: "Ezdrás könyve",
    16: "Nehémiás könyve",
    17: "Eszter könyve",
    18: "Jób könyve",
    19: "Zsoltárok könyve",
    20: "Példabeszédek könyve",
    21: "Prédikátor könyve",
    22: "Énekek éneke",
    23: "Ézsaiás prófétája",
    24: "Jeremiás prófétája",
    25: "Jeremiás siralmai",
    26: "Ezékiel prófétája",
    27: "Dániel prófétája",
    28: "Hóseás prófétája",
    29: "Jóel prófétája",
    30: "Ámos prófétája",
    31: "Abdiás prófétája",
    32: "Jónás prófétája",
    33: "Mikeás prófétája",
    34: "Náhum prófétája",
    35: "Habakuk prófétája",
    36: "Szofóniás prófétája",
    37: "Aggeus prófétája",
    38: "Zakariás prófétája",
    39: "Malakiás prófétája",
    40: "Máté evangéliuma",
    41: "Márk evangéliuma",
    42: "Lukács evengeliuma",
    43: "János evengeliuma",
    44: "Az apostolok cselekedetei",
    45: "A rómaiakhoz írt levél",
    46: "A korintusiakhoz írt első levél",
    47: "A korintusiakhoz írt második levél",
    48: "A galatákhoz írt levél",
    49: "Az efezusiakhoz írt levél",
    50: "A filippiekhez írt levél",
    51: "A kolosséiakhoz írt levél",
    52: "A tesszalonikiekhez írt első levél",
    53: "A tesszalonikiekhez írt második levél",
    54: "A timóteushoz írt első levél",
    55: "A timóteushoz írt második levél",
    56: "Títushoz írt levél",
    57: "Filemonhoz írt levél",
    58: "A zsidókhoz írt levél",
    59: "Jakab levele",
    60: "Péter első levele",
    61: "Péter második levele",
    62: "János első levele",
    63: "János második levele",
    64: "János harmadik levele",
    65: "Júdás levele",
    66: "Jelenések könyve",
}

CZECH_BOOK_NAMES = {
    1: "Genesis",
    2: "Exodus",
    3: "Leviticus",
    4: "Numeri",
    5: "Deuteronomium",
    6: "Jozue",
    7: "Soudců",
    8: "Rút",
    9: "1 Samuelova",
    10: "2 Samuelova",
    11: "1 Královská",
    12: "2 Královská",
    13: "1 Paralipomenon",
    14: "2 Paralipomenon",
    15: "Ezdra",
    16: "Nehemiáš",
    17: "Estera",
    18: "Jób",
    19: "Žalmy",
    20: "Přísloví",
    21: "Kazatel",
    22: "Píseň písní",
    23: "Izaiáš",
    24: "Jeremiáš",
    25: "Pláč",
    26: "Ezechiel",
    27: "Daniel",
    28: "Ozeáš",
    29: "Joel",
    30: "Amos",
    31: "Abdijáš",
    32: "Jonáš",
    33: "Micheáš",
    34: "Nahum",
    35: "Abakuk",
    36: "Sofoniáš",
    37: "Ageus",
    38: "Zachariáš",
    39: "Maleachi",
    40: "Matouš",
    41: "Marek",
    42: "Lukáš",
    43: "Jan",
    44: "Skutky apoštolů",
    45: "Římanům",
    46: "1 Korintským",
    47: "2 Korintským",
    48: "Galatským",
    49: "Efeským",
    50: "Filipským",
    51: "Koloským",
    52: "1 Tesalonickým",
    53: "2 Tesalonickým",
    54: "1 Timoteovi",
    55: "2 Timoteovi",
    56: "Titovi",
    57: "Filemonovi",
    58: "Židům",
    59: "Jakubův",
    60: "1 Petrův",
    61: "2 Petrův",
    62: "1 Janův",
    63: "2 Janův",
    64: "3 Janův",
    65: "Judův",
    66: "Zjevení",
}

ROMANIAN_BOOK_NAMES = {
    1: "Geneza",
    2: "Exodul",
    3: "Leviticul",
    4: "Numerii",
    5: "Deuteronomul",
    6: "Iosua",
    7: "Judecători",
    8: "Rut",
    9: "1 Samuel",
    10: "2 Samuel",
    11: "1 Împăraţi",
    12: "2 Împăraţi",
    13: "1 Cronici",
    14: "2 Cronici",
    15: "Ezra",
    16: "Neemia",
    17: "Estera",
    18: "Iov",
    19: "Psalmii",
    20: "Proverbele",
    21: "Ecleziastul",
    22: "Cântarea Cântărilor",
    23: "Isaia",
    24: "Ieremia",
    25: "Plângerile lui Ieremia",
    26: "Ezechiel",
    27: "Daniel",
    28: "Osea",
    29: "Ioel",
    30: "Amos",
    31: "Obadia",
    32: "Iona",
    33: "Micheea",
    34: "Naum",
    35: "Habacuc",
    36: "Sofonia",
    37: "Hagai",
    38: "Zaharia",
    39: "Maleahi",
    40: "Matei",
    41: "Marcu",
    42: "Luca",
    43: "Ioan",
    44: "Faptele Apostolilor",
    45: "Romani",
    46: "1 Corinteni",
    47: "2 Corinteni",
    48: "Galateni",
    49: "Efeseni",
    50: "Filipeni",
    51: "Coloseni",
    52: "1 Tesaloniceni",
    53: "2 Tesaloniceni",
    54: "1 Timotei",
    55: "2 Timotei",
    56: "Tit",
    57: "Filimon",
    58: "Evrei",
    59: "Iacov",
    60: "1 Petru",
    61: "2 Petru",
    62: "1 Ioan",
    63: "2 Ioan",
    64: "3 Ioan",
    65: "Iuda",
    66: "Apocalipsa",
}

GREEK_BOOK_NAMES = {
    1: "Γένεση",
    2: "Έξοδος",
    3: "Λευιτικός",
    4: "Αριθμοί",
    5: "Δευτερονόμιο",
    6: "Ιησούς του Ναυή",
    7: "Κριτές",
    8: "Ρουθ",
    9: "1 Σαμουήλ",
    10: "2 Σαμουήλ",
    11: "1 Βασιλειών",
    12: "2 Βασιλειών",
    13: "1 Παραλειπομένων",
    14: "2 Παραλειπομένων",
    15: "Έσδρας",
    16: "Νεεμίας",
    17: "Εσθήρ",
    18: "Ιώβ",
    19: "Ψαλμοί",
    20: "Παροιμίες",
    21: "Εκκλησιαστής",
    22: "Άσμα Ασμάτων",
    23: "Ησαΐας",
    24: "Ιερεμίας",
    25: "Θρήνοι",
    26: "Ιεζεκιήλ",
    27: "Δανιήλ",
    28: "Ωσηέ",
    29: "Ιωήλ",
    30: "Αμώς",
    31: "Αβδιού",
    32: "Ιωνάς",
    33: "Μιχαίας",
    34: "Ναούμ",
    35: "Αβακούμ",
    36: "Σοφονίας",
    37: "Αγγαίος",
    38: "Ζαχαρίας",
    39: "Μαλαχίας",
    40: "Ματθαίος",
    41: "Μάρκος",
    42: "Λουκάς",
    43: "Ιωάννης",
    44: "Πράξεις Αποστόλων",
    45: "Ρωμαίους",
    46: "1 Κορινθίους",
    47: "2 Κορινθίους",
    48: "Γαλάτας",
    49: "Εφεσίους",
    50: "Φιλιππησίους",
    51: "Κολοσσαείς",
    52: "1 Θεσσαλονικείς",
    53: "2 Θεσσαλονικείς",
    54: "1 Τιμόθεο",
    55: "2 Τιμόθεο",
    56: "Τίτον",
    57: "Φιλήμονα",
    58: "Εβραίους",
    59: "Ιακώβου",
    60: "1 Πέτρου",
    61: "2 Πέτρου",
    62: "1 Ιωάννου",
    63: "2 Ιωάννου",
    64: "3 Ιωάννου",
    65: "Ιούδα",
    66: "Αποκάλυψη",
}

TURKISH_BOOK_NAMES = {
    1: "Yaratılış",
    2: "Çıkış",
    3: "Levililer",
    4: "Sayılar",
    5: "Yasanın Tekrarı",
    6: "Yeşu",
    7: "Hakimler",
    8: "Rut",
    9: "1. Samuel",
    10: "2. Samuel",
    11: "1. Krallar",
    12: "2. Krallar",
    13: "1. Tarihler",
    14: "2. Tarihler",
    15: "Ezra",
    16: "Nehemya",
    17: "Ester",
    18: "Eyüp",
    19: "Zebur",
    20: "Meseller",
    21: "Vaiz",
    22: "Ezgiler Ezgisi",
    23: "Yeşaya",
    24: "Yeremya",
    25: "Ağıtlar",
    26: "Hezekiel",
    27: "Daniel",
    28: "Hoşea",
    29: "Yoel",
    30: "Amos",
    31: "Obadya",
    32: "Yunus",
    33: "Mika",
    34: "Nahum",
    35: "Habakkuk",
    36: "Sefanya",
    37: "Haggay",
    38: "Zekeriya",
    39: "Malaki",
    40: "Matta",
    41: "Markos",
    42: "Luka",
    43: "Yuhanna",
    44: "Elçilerin İşleri",
    45: "Romalılar",
    46: "1. Korintliler",
    47: "2. Korintliler",
    48: "Galatyalılar",
    49: "Efesliler",
    50: "Filipililer",
    51: "Koloseliler",
    52: "1. Selanikliler",
    53: "2. Selanikliler",
    54: "1. Timoteos",
    55: "2. Timoteos",
    56: "Titus",
    57: "Filimon",
    58: "İbraniler",
    59: "Yakup",
    60: "1. Petrus",
    61: "2. Petrus",
    62: "1. Yuhanna",
    63: "2. Yuhanna",
    64: "3. Yuhanna",
    65: "Yahuda",
    66: "Vahiy",
}

AFRIKAANS_BOOK_NAMES = {
    1: "Genesis",
    2: "Eksodus",
    3: "Levitikus",
    4: "Numeri",
    5: "Deuteronomium",
    6: "Josua",
    7: "Rigters",
    8: "Rut",
    9: "1 Samuel",
    10: "2 Samuel",
    11: "1 Konings",
    12: "2 Konings",
    13: "1 Kronieke",
    14: "2 Kronieke",
    15: "Esra",
    16: "Nehemia",
    17: "Ester",
    18: "Job",
    19: "Psalm",
    20: "Spreuke",
    21: "Prediker",
    22: "Hooglied",
    23: "Jesaja",
    24: "Jeremia",
    25: "Klaagliedere",
    26: "Esegiel",
    27: "Daniël",
    28: "Hosea",
    29: "Joël",
    30: "Amos",
    31: "Obadja",
    32: "Jona",
    33: "Miga",
    34: "Nahum",
    35: "Habakuk",
    36: "Sefanja",
    37: "Haggae",
    38: "Sagaria",
    39: "Maleagi",
    40: "Matteus",
    41: "Markus",
    42: "Lukas",
    43: "Johannes",
    44: "Handelinge",
    45: "Romeine",
    46: "1 Korintiërs",
    47: "2 Korintiërs",
    48: "Galasiërs",
    49: "Efesiërs",
    50: "Filippense",
    51: "Kolossense",
    52: "1 Tessalonisense",
    53: "2 Tessalonisense",
    54: "1 Timoteus",
    55: "2 Timoteus",
    56: "Titus",
    57: "Filemon",
    58: "Hebreërs",
    59: "Jakobus",
    60: "1 Petrus",
    61: "2 Petrus",
    62: "1 Johannes",
    63: "2 Johannes",
    64: "3 Johannes",
    65: "Judas",
    66: "Openbaring",
}

ALBANIAN_BOOK_NAMES = {
    1: "Zanafilla",
    2: "Eksodi",
    3: "Levitiku",
    4: "Numrat",
    5: "Ligji i Përtërirë",
    6: "Joshuë",
    7: "Gjykëvet",
    8: "Ruti",
    9: "1 Samueli",
    10: "2 Samueli",
    11: "1 Mbretërve",
    12: "2 Mbretërve",
    13: "1 Kronikave",
    14: "2 Kronikave",
    15: "Ezra",
    16: "Nehemia",
    17: "Estër",
    18: "Jobi",
    19: "Psalmet",
    20: "Fjalët e Urta",
    21: "Predikuesi",
    22: "Kënga e Këngëve",
    23: "Isaia",
    24: "Jeremia",
    25: "Vajët",
    26: "Ezekieli",
    27: "Danieli",
    28: "Osea",
    29: "Joeli",
    30: "Amosi",
    31: "Abdia",
    32: "Jonai",
    33: "Mikeaja",
    34: "Nahumi",
    35: "Habakuku",
    36: "Sofonia",
    37: "Hagai",
    38: "Zakaria",
    39: "Malakias",
    40: "Mateu",
    41: "Marku",
    42: "Luka",
    43: "Gjoni",
    44: "Veprat e Apostujve",
    45: "Romanëve",
    46: "1 Korintasve",
    47: "2 Korintasve",
    48: "Galatasve",
    49: "Efesasve",
    50: "Filiposve",
    51: "Kolasasve",
    52: "1 Selanikasve",
    53: "2 Selanikasve",
    54: "1 Timoteut",
    55: "2 Timoteut",
    56: "Titusit",
    57: "Filemonit",
    58: "Hebrenjve",
    59: "Jakubit",
    60: "1 Pjetrit",
    61: "2 Pjetrit",
    62: "1 Gjonit",
    63: "2 Gjonit",
    64: "3 Gjonit",
    65: "Judës",
    66: "Zbulesa",
}

ARABIC_BOOK_NAMES = {
    1: "التكوين",
    2: "الخروج",
    3: "اللاويين",
    4: "الأعداد",
    5: "التثنية",
    6: "يشوع",
    7: "القضاة",
    8: "راعوث",
    9: "صموئيل الأول",
    10: "صموئيل الثاني",
    11: "ملوك الأول",
    12: "ملوك الثاني",
    13: "أخبار الأول",
    14: "أخبار الثاني",
    15: "عزرا",
    16: "نحميا",
    17: "أستير",
    18: "أيوب",
    19: "المزامير",
    20: "الأمثال",
    21: "الجامعة",
    22: "نشيد الأنشاد",
    23: "إشعياء",
    24: "إرميا",
    25: "مراثي إرميا",
    26: "حزقيال",
    27: "دانيال",
    28: "هوشع",
    29: "يؤيل",
    30: "عاموس",
    31: "عوباديا",
    32: "يونان",
    33: "ميخا",
    34: "ناحوم",
    35: "حبقوق",
    36: "صفنيا",
    37: "حجي",
    38: "زكريا",
    39: "ملاخي",
    40: "متى",
    41: "مرقس",
    42: "لوقا",
    43: "يوحنا",
    44: "أعمال الرسل",
    45: "رومية",
    46: "كورنثوس الأولى",
    47: "كورنثوس الثانية",
    48: "غلاطية",
    49: "أفسس",
    50: "فيلبي",
    51: "كولوسي",
    52: "تسالونيكي الأولى",
    53: "تسالونيكي الثانية",
    54: "تيموثاوس الأولى",
    55: "تيموثاوس الثانية",
    56: "تيطس",
    57: "فليمون",
    58: "العبرانيين",
    59: "يعقوب",
    60: "بطرس الأولى",
    61: "بطرس الثانية",
    62: "يوحنا الأولى",
    63: "يوحنا الثانية",
    64: "يوحنا الثالثة",
    65: "يهوذا",
    66: "رؤيا",
}

BASQUE_BOOK_NAMES = {
    1: "Sortalaxe",
    2: "Irteera",
    3: "Legearen Liburua",
    4: "Zenbakiak",
    5: "Deuteronomioa",
    6: "Josue",
    7: "Epaileak",
    8: "Rut",
    9: "Samuel I",
    10: "Samuel II",
    11: "Errege I",
    12: "Errege II",
    13: "Kronika I",
    14: "Kronika II",
    15: "Esdras",
    16: "Nehemias",
    17: "Ester",
    18: "Job",
    19: "Salmak",
    20: "Aholkuak",
    21: "Predikaria",
    22: "Kantuen Kanta",
    23: "Isaias",
    24: "Jeremias",
    25: "Negar Kantak",
    26: "Ezekiel",
    27: "Daniel",
    28: "Oseas",
    29: "Joel",
    30: "Amos",
    31: "Abdias",
    32: "Jonas",
    33: "Mika",
    34: "Nahum",
    35: "Habakuk",
    36: "Sofonias",
    37: "Ageo",
    38: "Zakarias",
    39: "Maleakias",
    40: "Mateo",
    41: "Markos",
    42: "Luka",
    43: "Jon",
    44: "Apostoluen Ekintzak",
    45: "Erromatarrei",
    46: "Korintoarrei I",
    47: "Korintoarrei II",
    48: "Galaziarrei",
    49: "Efesoarrei",
    50: "Filipiarrei",
    51: "Kolosasarrei",
    52: "Tesalonikarrei I",
    53: "Tesalonikarrei II",
    54: "Timoteori I",
    55: "Timoteori II",
    56: "Titori",
    57: "Filemoni",
    58: "Hebrearrei",
    59: "Jakobo",
    60: "Petri I",
    61: "Petri II",
    62: "Jon I",
    63: "Jon II",
    64: "Jon III",
    65: "Judas",
    66: "Apokalipsia",
}

BELARUSIAN_BOOK_NAMES = {
    1: "Быццё",
    2: "Выхад",
    3: "Левіт",
    4: "Лічбы",
    5: "Другі Закон",
    6: "Ісус Навін",
    7: "Кніга Суддзяў",
    8: "Рут",
    9: "1-я Царства",
    10: "2-я Царства",
    11: "3-я Царства",
    12: "4-я Царства",
    13: "1-я Параліпяменан",
    14: "2-я Параліпяменан",
    15: "Эздра",
    16: "Нямэмія",
    17: "Эсфір",
    18: "Іоў",
    19: "Псалтыр",
    20: "Прытчы",
    21: "Эклізіяст",
    22: "Песня Песняў",
    23: "Ісая",
    24: "Іерэмія",
    25: "Плач Іерэміі",
    26: "Іезекіль",
    27: "Данііл",
    28: "Асія",
    29: "Іоіль",
    30: "Амас",
    31: "Аўдыя",
    32: "Іона",
    33: "Міхей",
    34: "Навум",
    35: "Абакум",
    36: "Сафанія",
    37: "Агей",
    38: "Захарыя",
    39: "Малахіі",
    40: "Матфей",
    41: "Марк",
    42: "Лука",
    43: "Іаан",
    44: "Дзеі Апосталаў",
    45: "Рымлянам",
    46: "1 Карынфянам",
    47: "2 Карынфянам",
    48: "Галатам",
    49: "Эфэсянам",
    50: "Філіпянам",
    51: "Каласянам",
    52: "1 Фесаланікійцам",
    53: "2 Фесаланікійцам",
    54: "1 Цімафею",
    55: "2 Цімафею",
    56: "Ціту",
    57: "Філімону",
    58: "Яўрэям",
    59: "Якава",
    60: "1 Пятра",
    61: "2 Пятра",
    62: "1 Іаана",
    63: "2 Іаана",
    64: "3 Іаана",
    65: "Іуды",
    66: "Адкрыццё",
}

BULGARIAN_BOOK_NAMES = {
    1: "Битие",
    2: "Изход",
    3: "Левит",
    4: "Числа",
    5: "Второзаконие",
    6: "Иисус Навин",
    7: "Книга на съдиите",
    8: "Рут",
    9: "1 Царства",
    10: "2 Царства",
    11: "3 Царства",
    12: "4 Царства",
    13: "1 Летописи",
    14: "2 Летописи",
    15: "Ездра",
    16: "Неемия",
    17: "Естер",
    18: "Йов",
    19: "Псалми",
    20: "Притчи",
    21: "Еклисиаст",
    22: "Песен на песните",
    23: "Исая",
    24: "Еремия",
    25: "Плачът на Еремия",
    26: "Езекиил",
    27: "Даниил",
    28: "Осия",
    29: "Йоел",
    30: "Амос",
    31: "Авдий",
    32: "Йона",
    33: "Михей",
    34: "Наум",
    35: "Аввакум",
    36: "Софония",
    37: "Агей",
    38: "Захария",
    39: "Малахия",
    40: "Матей",
    41: "Марко",
    42: "Лука",
    43: "Йоан",
    44: "Деяния",
    45: "Римляни",
    46: "1 Коринтяни",
    47: "2 Коринтяни",
    48: "Галатяни",
    49: "Ефесяни",
    50: "Филипяни",
    51: "Колосяни",
    52: "1 Солунци",
    53: "2 Солунци",
    54: "1 Тимотей",
    55: "2 Тимотей",
    56: "Тит",
    57: "Филимон",
    58: "Евреи",
    59: "Яков",
    60: "1 Петър",
    61: "2 Петър",
    62: "1 Йоан",
    63: "2 Йоан",
    64: "3 Йоан",
    65: "Юда",
    66: "Откровение",
}

CHINESE_BOOK_NAMES = {
    1: "創世記",
    2: "出埃及記",
    3: "利未記",
    4: "民數記",
    5: "申命記",
    6: "約書亞記",
    7: "士師記",
    8: "路得記",
    9: "撒母耳記上",
    10: "撒母耳記下",
    11: "列王紀上",
    12: "列王紀下",
    13: "歷代志上",
    14: "歷代志下",
    15: "以斯拉記",
    16: "尼希米記",
    17: "以斯帖記",
    18: "約伯記",
    19: "詩篇",
    20: "箴言",
    21: "傳道書",
    22: "雅歌",
    23: "以賽亞書",
    24: "耶利米書",
    25: "耶利米哀歌",
    26: "以西結書",
    27: "但以理書",
    28: "何西阿書",
    29: "約珥書",
    30: "阿摩司書",
    31: "俄巴底亞書",
    32: "約拿書",
    33: "彌迦書",
    34: "那鴻書",
    35: "哈巴谷書",
    36: "西番雅書",
    37: "哈該書",
    38: "撒加利亞書",
    39: "瑪拉基書",
    40: "馬太福音",
    41: "馬可福音",
    42: "路加福音",
    43: "約翰福音",
    44: "使徒行傳",
    45: "羅馬書",
    46: "哥林多前書",
    47: "哥林多後書",
    48: "加拉太書",
    49: "以弗所書",
    50: "腓立比書",
    51: "歌羅西書",
    52: "帖撒羅尼迦前書",
    53: "帖撒羅尼迦後書",
    54: "提摩太前書",
    55: "提摩太後書",
    56: "提多書",
    57: "腓利門書",
    58: "希伯來書",
    59: "雅各書",
    60: "彼得前書",
    61: "彼得後書",
    62: "約翰一書",
    63: "約翰二書",
    64: "約翰三書",
    65: "猶大書",
    66: "啟示錄",
}

HEBREW_BOOK_NAMES = {
    1: "בראשית",
    2: "שמות",
    3: "ויקרא",
    4: "במדבר",
    5: "דברים",
    6: "יהושע",
    7: "שופטים",
    8: "רות",
    9: "שמואל א",
    10: "שמואל ב",
    11: "מלכים א",
    12: "מלכים ב",
    13: "דברי הימים א",
    14: "דברי הימים ב",
    15: "עזרא",
    16: "נחמיה",
    17: "אסתר",
    18: "איוב",
    19: "תהילים",
    20: "משלי",
    21: "קהלת",
    22: "שיר השירים",
    23: "ישעיה",
    24: "ירמיה",
    25: "איכה",
    26: "יחזקאל",
    27: "דניאל",
    28: "הושע",
    29: "יואל",
    30: "עמוס",
    31: "עובדיה",
    32: "יונה",
    33: "מיכה",
    34: "נחום",
    35: "חבקוק",
    36: "צפניה",
    37: "חגי",
    38: "זכריה",
    39: "מלאכי",
    40: "מתי",
    41: "מרקוס",
    42: "לוקא",
    43: "יוחנן",
    44: "מעשי השליחים",
    45: "רומיים",
    46: "קורינתים א",
    47: "קורינתים ב",
    48: "גלטים",
    49: "אפסים",
    50: "פיליפים",
    51: "קולוסים",
    52: "תסלוניקים א",
    53: "תסלוניקים ב",
    54: "טימותיאוס א",
    55: "טימותיאוס ב",
    56: "טיטוס",
    57: "פילמון",
    58: "עברים",
    59: "יעקב",
    60: "פטרוס א",
    61: "פטרוס ב",
    62: "יוחנן א",
    63: "יוחנן ב",
    64: "יוחנן ג",
    65: "יהודה",
    66: "התגלות",
}

KOREAN_BOOK_NAMES = {
    1: "창세기",
    2: "출애굽기",
    3: "레위기",
    4: "민수기",
    5: "신명기",
    6: "여호수아",
    7: "사사기",
    8: "룻기",
    9: "사무엘상",
    10: "사무엘하",
    11: "열왕기상",
    12: "열왕기하",
    13: "역대상",
    14: "역대하",
    15: "에스라",
    16: "느헤미야",
    17: "에스더",
    18: "욥기",
    19: "시편",
    20: "잠언",
    21: "전도서",
    22: "아가",
    23: "이사야",
    24: "예레미야",
    25: "예레미야애가",
    26: "에스겔",
    27: "다니엘",
    28: "호세아",
    29: "요엘",
    30: "아모스",
    31: "오바댜",
    32: "요나",
    33: "미가",
    34: "나훔",
    35: "하박국",
    36: "스바냐",
    37: "학개",
    38: "스가랴",
    39: "말라기",
    40: "마태복음",
    41: "마가복음",
    42: "누가복음",
    43: "요한복음",
    44: "사도행전",
    45: "로마서",
    46: "고린도전서",
    47: "고린도후서",
    48: "갈라디아서",
    49: "에베소서",
    50: "빌립보서",
    51: "골로새서",
    52: "데살로니가전서",
    53: "데살로니가후서",
    54: "디모데전서",
    55: "디모데후서",
    56: "디도서",
    57: "빌레몬서",
    58: "히브리서",
    59: "야고보서",
    60: "베드로전서",
    61: "베드로후서",
    62: "요한일서",
    63: "요한이서",
    64: "요한삼서",
    65: "유다서",
    66: "요한계시록",
}

LATIN_BOOK_NAMES = {
    1: "Genesis",
    2: "Exodus",
    3: "Leviticus",
    4: "Numeri",
    5: "Deuteronomium",
    6: "Iosue",
    7: "Iudicum",
    8: "Ruth",
    9: "1 Samuel",
    10: "2 Samuel",
    11: "1 Regum",
    12: "2 Regum",
    13: "1 Paralipomenon",
    14: "2 Paralipomenon",
    15: "Esdras",
    16: "Neemias",
    17: "Esther",
    18: "Iob",
    19: "Psalmi",
    20: "Proverbia",
    21: "Ecclesiastes",
    22: "Canticum Canticorum",
    23: "Isaias",
    24: "Ieremias",
    25: "Lamentationes",
    26: "Ezechiel",
    27: "Daniel",
    28: "Osee",
    29: "Ioel",
    30: "Amos",
    31: "Abdias",
    32: "Ionas",
    33: "Michaeas",
    34: "Nahum",
    35: "Habacuc",
    36: "Sophonias",
    37: "Aggaeus",
    38: "Zacharias",
    39: "Malachias",
    40: "Matthaeus",
    41: "Marcus",
    42: "Lucas",
    43: "Ioannes",
    44: "Actus Apostolorum",
    45: "Ad Romanos",
    46: "1 Corinthios",
    47: "2 Corinthios",
    48: "Ad Galatas",
    49: "Ad Ephesios",
    50: "Ad Philippenses",
    51: "Ad Colossenses",
    52: "1 Thessalonissenses",
    53: "2 Thessalonissenses",
    54: "1 Timotheum",
    55: "2 Timotheum",
    56: "Ad Titum",
    57: "Ad Philemonem",
    58: "Ad Hebraeos",
    59: "Iacobi",
    60: "1 Petri",
    61: "2 Petri",
    62: "1 Ioannis",
    63: "2 Ioannis",
    64: "3 Ioannis",
    65: "Iudae",
    66: "Apocalypsis",
}

VIETNAMESE_BOOK_NAMES = {
    1: "Sáng Thế",
    2: "Xuất Hành",
    3: "Lê-vi",
    4: "Dân Số",
    5: "Phục Hồi",
    6: "Giô-suê",
    7: "Các Thẩm Phán",
    8: "Ru-tô",
    9: "1 Sa-mu-ên",
    10: "2 Sa-mu-ên",
    11: "1 Các Vua",
    12: "2 Các Vua",
    13: "1 Sử Ký",
    14: "2 Sử Ký",
    15: "E-xra",
    16: "Nê-hê-mi",
    17: "E-xte",
    18: "Gióp",
    19: "Thi Thiên",
    20: "Châm Ngôn",
    21: "Truyền Đạo",
    22: "Nhã Ca",
    23: "Y-sâ-xa",
    24: "Giê-rê-mi",
    25: "Ca Thương",
    26: "Ê-xê-chên",
    27: "Đa-ni-ên",
    28: "Hô-xê-a",
    29: "Y-ô-ên",
    30: "A-mốt",
    31: "Áp-đi-a",
    32: "Giô-na",
    33: "Mi-chê",
    34: "Na-hum",
    35: "Ha-ba-cúc",
    36: "Sô-phô-ni-a",
    37: "A-ga-i",
    38: "Xa-cha-ri",
    39: "Ma-la-chi",
    40: "Ma-thi-ơ",
    41: "Mác-cô",
    42: "Lu-ca",
    43: "Giô-han",
    44: "Công Vụ",
    45: "Rô-ma",
    46: "1 Cô-rinh-tô",
    47: "2 Cô-rinh-tô",
    48: "Ga-la-ti",
    49: "Ê-phê-sô",
    50: "Phi-líp",
    51: "Cô-lô-se",
    52: "1 Tê-sa-lô-ni-ca",
    53: "2 Tê-sa-lô-ni-ca",
    54: "1 Ti-mô-thê",
    55: "2 Ti-mô-thê",
    56: "Ti-tô",
    57: "Phi-lê-môn",
    58: "Hê-bơ-rơ",
    59: "Gia-cơ",
    60: "1 Phi-e-rơ",
    61: "2 Phi-e-rơ",
    62: "1 Giô-han",
    63: "2 Giô-han",
    64: "3 Giô-han",
    65: "Giu-đa",
    66: "Khải Huyền",
}

HINDI_BOOK_NAMES = {
    1: "उत्पत्ति",
    2: "निर्गमन",
    3: "लेवी",
    4: "गिनती",
    5: "व्यवस्था",
    6: "यहोशू",
    7: "न्यायियों",
    8: "रूत",
    9: "1 शमूएल",
    10: "2 शमूएल",
    11: "1 राजा",
    12: "2 राजा",
    13: "1 इतिहास",
    14: "2 इतिहास",
    15: "एज्रा",
    16: "नहेमायाह",
    17: "एस्तेर",
    18: "अय्यूब",
    19: "भजन",
    20: "हिल्कुली",
    21: "सभोपदेशक",
    22: "गीत",
    23: "यशायाह",
    24: "यिर्मायाह",
    25: "विलाप",
    26: "यहेजकेल",
    27: "दानिय्येल",
    28: "होशे",
    29: "योएल",
    30: "आमोस",
    31: "ओबद्याह",
    32: "योना",
    33: "मीका",
    34: "नहूम",
    35: "हबक्कूक",
    36: "सफन्याह",
    37: "हग्गै",
    38: "जकर्याह",
    39: "मलाखी",
    40: "मत्ती",
    41: "मर्कूस",
    42: "लूका",
    43: "यूहन्ना",
    44: "प्रेरितों के कृत्य",
    45: "रोमियों",
    46: "1 कुरिन्थियों",
    47: "2 कुरिन्थियों",
    48: "गलातियों",
    49: "इफिसियों",
    50: "फिलिप्पियों",
    51: "कलस्सियों",
    52: "1 थिस्सलुनीकियों",
    53: "2 थिस्सलुनीकियों",
    54: "1 तीमुथियुस",
    55: "2 तीमुथियुस",
    56: "तीतुस",
    57: "फिलेमोन",
    58: "इब्रानियों",
    59: "याकूब",
    60: "1 पतरस",
    61: "2 पतरस",
    62: "1 यूहन्ना",
    63: "2 यूहन्ना",
    64: "3 यूहन्ना",
    65: "यहूदा",
    66: "प्रकाशित वाणी",
}

TAMIL_BOOK_NAMES = {
    1: "ஆதியாகமம்",
    2: "விடுவதற்கு",
    3: "லேவியர்",
    4: "எண்ணிக்கை",
    5: "துவக்கச் சட்டம்",
    6: "யோசுவா",
    7: "நியாயாதிபதிகள்",
    8: "ரூத்",
    9: "1 சமுவேல்",
    10: "2 சமுவேல்",
    11: "1 அரசர்கள்",
    12: "2 அரசர்கள்",
    13: "1 நாளாகமம்",
    14: "2 நாளாகமம்",
    15: "எஸ்ரா",
    16: "நெகேமியா",
    17: "எஸ்தர்",
    18: "இல்",
    19: "திருப்பாடல்கள்",
    20: "நீதிமொழிகள்",
    21: "பிரசங்கி",
    22: "பாடல்",
    23: "எசாயா",
    24: "எரேமியா",
    25: "புலம்பல்",
    26: "எசேக்கியேல்",
    27: "தானியேல்",
    28: "ஓசியா",
    29: "யோவேல்",
    30: "ஆமோஸ்",
    31: "ஒபதியா",
    32: "யோனா",
    33: "மீகா",
    34: "நாகூம்",
    35: "அபகூக்",
    36: "சோப்போனியா",
    37: "அக்கை",
    38: "சகரியா",
    39: "மலாகி",
    40: "மதேயு",
    41: "மாற்கு",
    42: "லுக்கா",
    43: "யோவான்",
    44: "திருத்தூதர்கள்",
    45: "ரோமர்",
    46: "1 கொரிந்தியர்",
    47: "2 கொரிந்தியர்",
    48: "கலாத்தியர்",
    49: "எபேசியர்",
    50: "பிலிப்பியர்",
    51: "கொலோசெயர்",
    52: "1 தெசலோனிக்கியர்",
    53: "2 தெசலோனிக்கியர்",
    54: "1 திமோதேயு",
    55: "2 திமோதேயு",
    56: "தீது",
    57: "பிலேமோன்",
    58: "எபிரேயர்",
    59: "யாக்கோபு",
    60: "1 பேதுரு",
    61: "2 பேதுரு",
    62: "1 யோவான்",
    63: "2 யோவான்",
    64: "3 யோவான்",
    65: "யூதா",
    66: "வெளிப்படுத்தல்",
}

THAI_BOOK_NAMES = {
    1: "ปฐมกาล",
    2: "อพยพ",
    3: "เลวีนิติ",
    4: "กันดารวิถี",
    5: "เฉลยธรรมบัญญัติ",
    6: "โยชูวา",
    7: "ผู้วินิจฉัย",
    8: "นางรูธ",
    9: "1 ซามูเอล",
    10: "2 ซามูเอล",
    11: "1 กษัตริย์",
    12: "2 กษัตริย์",
    13: "1 พงศ์กษัตริย์",
    14: "2 พงศ์กษัตริย์",
    15: "เอสรา",
    16: "เนหะมี",
    17: "เอสเธอร์",
    18: "โยบ",
    19: "เพลงสดุดี",
    20: "สุภาพิทานปัญญา",
    21: "ประกาศก",
    22: "เพลงซาโลมอน",
    23: "อิสยาห์",
    24: "เยเรมีย์",
    25: "คร่ำครวญ",
    26: "เอเสเคียล",
    27: "ดาเนียล",
    28: "โฮเชยา",
    29: "โยเอล",
    30: "อาโมส",
    31: "ออบดียาห์",
    32: "โยนาห์",
    33: "มีคาห์",
    34: "นาฮูม",
    35: "ฮาบากุก",
    36: "โซโปนียาห์",
    37: "ฮักกาย",
    38: "เศคาริยาห์",
    39: "มาลาคี",
    40: "มัทธิว",
    41: "มาระโก",
    42: "ลูกา",
    43: "ยอห์น",
    44: "กิจการ",
    45: "โรม",
    46: "1 โครินโธ",
    47: "2 โครินโธ",
    48: "กาลาเทีย",
    49: "เอเฟซ",
    50: "ฟิลิปปี",
    51: "โคลอสี",
    52: "1 เทสะโลนิกะ",
    53: "2 เทสะโลนิกะ",
    54: "1 ทิโมธี",
    55: "2 ทิโมธี",
    56: "ทิตัส",
    57: "ฟิลีมอน",
    58: "ฮีบรู",
    59: "ยากอบ",
    60: "1 เปโตร",
    61: "2 เปโตร",
    62: "1 โยฮัน",
    63: "2 โยฮัน",
    64: "3 โยฮัน",
    65: "ยูดา",
    66: "วิวรณ์",
}

CROATIAN_BOOK_NAMES = {
    1: "Postanak",
    2: "Izlazak",
    3: "Levitički zakon",
    4: "Brojevi",
    5: "Ponovljeni zakon",
    6: "Jošua",
    7: "Suci",
    8: "Ruta",
    9: "1 Samuelova",
    10: "2 Samuelova",
    11: "1 Kraljevska",
    12: "2 Kraljevska",
    13: "1 Ljetopisi",
    14: "2 Ljetopisi",
    15: "Ezra",
    16: "Nehemija",
    17: "Ester",
    18: "Job",
    19: "Psalmi",
    20: "Poslovice",
    21: "Propovjednik",
    22: "Pjesma nad pjesmama",
    23: "Izaija",
    24: "Jeremija",
    25: "Tužaljke",
    26: "Ezekiel",
    27: "Daniel",
    28: "Hošea",
    29: "Joel",
    30: "Amos",
    31: "Obadija",
    32: "Jona",
    33: "Mika",
    34: "Nahum",
    35: "Habakuk",
    36: "Sefanija",
    37: "Hagai",
    38: "Zaharija",
    39: "Malahija",
    40: "Matej",
    41: "Marko",
    42: "Luka",
    43: "Ivan",
    44: "Djela apostolska",
    45: "Rimljanima",
    46: "1 Korinćanima",
    47: "2 Korinćanima",
    48: "Galatima",
    49: "Efežanima",
    50: "Filipljanima",
    51: "Kološanima",
    52: "1 Solunjanima",
    53: "2 Solunjanima",
    54: "1 Timoteju",
    55: "2 Timoteju",
    56: "Titu",
    57: "Filemonu",
    58: "Hebrejima",
    59: "Jakovljeva",
    60: "1 Petrova",
    61: "2 Petrova",
    62: "1 Ivanova",
    63: "2 Ivanova",
    64: "3 Ivanova",
    65: "Judina",
    66: "Otkrivenje",
}

LATVIAN_BOOK_NAMES = {
    1: "Radīšana",
    2: "Iziešana",
    3: "Levitiem",
    4: "Cilvēku skaitīšana",
    5: "Atkārtotais likums",
    6: "Jozue",
    7: "Soģi",
    8: "Rūta",
    9: "1. Samuēla",
    10: "2. Samuēla",
    11: "1. Ķēniņu",
    12: "2. Ķēniņu",
    13: "1. Laiku",
    14: "2. Laiku",
    15: "Ezra",
    16: "Nehemija",
    17: "Estere",
    18: "Ēriks",
    19: "Psalmi",
    20: "Pamācības",
    21: "Mācītājs",
    22: "Dziesmu dziesma",
    23: "Jesaja",
    24: "Jeremija",
    25: "Raudu dziesmas",
    26: "Ecēhiēls",
    27: "Daniēls",
    28: "Hošēja",
    29: "Joēls",
    30: "Amoss",
    31: "Obadija",
    32: "Jona",
    33: "Mihs",
    34: "Nahums",
    35: "Habakuka",
    36: "Cefanija",
    37: "Hagajs",
    38: "Zeharija",
    39: "Malehi",
    40: "Mateja",
    41: "Marks",
    42: "Lūka",
    43: "Jānis",
    44: "Apustuļu darbi",
    45: "Romiešiem",
    46: "1. Korintiešiem",
    47: "2. Korintiešiem",
    48: "Galatiešiem",
    49: "Efesiešiem",
    50: "Filipiešiem",
    51: "Kolosiešiem",
    52: "1. Tesaloniķiešiem",
    53: "2. Tesaloniķiešiem",
    54: "1. Timotejam",
    55: "2. Timotejam",
    56: "Titam",
    57: "Filemonam",
    58: "Ebrejiešiem",
    59: "Jēkaba",
    60: "1. Pētera",
    61: "2. Pētera",
    62: "1. Jāņa",
    63: "2. Jāņa",
    64: "3. Jāņa",
    65: "Jūdas",
    66: "Atklāsme",
}

CEBUANO_BOOK_NAMES = {
    1: "Genesis",
    2: "Exodo",
    3: "Levitico",
    4: "Numeros",
    5: "Deuteronomio",
    6: "Josue",
    7: "Mga Maghuhukom",
    8: "Rut",
    9: "1 Samuel",
    10: "2 Samuel",
    11: "1 Hari",
    12: "2 Hari",
    13: "1 Cronicas",
    14: "2 Cronicas",
    15: "Esdras",
    16: "Nehemias",
    17: "Ester",
    18: "Job",
    19: "Mga Salmo",
    20: "Mga Proverbio",
    21: "Ecclesiastes",
    22: "Awit ni Solomon",
    23: "Isaias",
    24: "Jeremias",
    25: "Mga Pagbangotan",
    26: "Ezequiel",
    27: "Daniel",
    28: "Oseas",
    29: "Joel",
    30: "Amos",
    31: "Abdias",
    32: "Jonas",
    33: "Miqueas",
    34: "Nahum",
    35: "Habacuc",
    36: "Sofonias",
    37: "Haggeo",
    38: "Zacarias",
    39: "Malaquias",
    40: "Mateo",
    41: "Marcos",
    42: "Lucas",
    43: "Juan",
    44: "Mga Buhat",
    45: "Roma",
    46: "1 Corinto",
    47: "2 Corinto",
    48: "Galacia",
    49: "Efeso",
    50: "Filipos",
    51: "Colosas",
    52: "1 Tesalonica",
    53: "2 Tesalonica",
    54: "1 Timoteo",
    55: "2 Timoteo",
    56: "Tito",
    57: "Filemon",
    58: "Hebreohanon",
    59: "Santiago",
    60: "1 Pedro",
    61: "2 Pedro",
    62: "1 Juan",
    63: "2 Juan",
    64: "3 Juan",
    65: "Judas",
    66: "Pinadayag",
}

SWAHILI_BOOK_NAMES = {
    1: "Mwanzo",
    2: "Kutoka",
    3: "Mambo ya Walawi",
    4: "Hesabu",
    5: "Kumbukumbu la Torati",
    6: "Yoshua",
    7: "Waamuzi",
    8: "Ruthu",
    9: "1 Samweli",
    10: "2 Samweli",
    11: "1 Wafalme",
    12: "2 Wafalme",
    13: "1 Mambo ya Nyakati",
    14: "2 Mambo ya Nyakati",
    15: "Ezra",
    16: "Nehemia",
    17: "Esta",
    18: "Ayubu",
    19: "Zaburi",
    20: "Mithali",
    21: "Mhubiri",
    22: "Wimbo Ulio Bora",
    23: "Isaya",
    24: "Yeremia",
    25: "Maombolezo",
    26: "Ezekieli",
    27: "Danieli",
    28: "Hosea",
    29: "Yoeli",
    30: "Amosi",
    31: "Obadia",
    32: "Yona",
    33: "Mika",
    34: "Nahumu",
    35: "Habakuki",
    36: "Sefania",
    37: "Hagai",
    38: "Zekaria",
    39: "Malaki",
    40: "Mathayo",
    41: "Marko",
    42: "Luka",
    43: "Yohana",
    44: "Matendo ya Mitume",
    45: "Warumi",
    46: "1 Wakorintho",
    47: "2 Wakorintho",
    48: "Wagalatia",
    49: "Waefeso",
    50: "Wafilipi",
    51: "Wakolosai",
    52: "1 Wathesalonike",
    53: "2 Wathesalonike",
    54: "1 Timotheo",
    55: "2 Timotheo",
    56: "Tito",
    57: "Filemoni",
    58: "Waebrania",
    59: "Yakobo",
    60: "1 Petro",
    61: "2 Petro",
    62: "1 Yohana",
    63: "2 Yohana",
    64: "3 Yohana",
    65: "Yuda",
    66: "Ufunuo",
}

TAGALOG_BOOK_NAMES = {
    1: "Genesis",
    2: "Exodo",
    3: "Levitico",
    4: "Mga Bilang",
    5: "Deuteronomio",
    6: "Josue",
    7: "Mga Hukom",
    8: "Ruth",
    9: "1 Samuel",
    10: "2 Samuel",
    11: "1 Mga Hari",
    12: "2 Mga Hari",
    13: "1 Mga Cronica",
    14: "2 Mga Cronica",
    15: "Ezra",
    16: "Nehemias",
    17: "Esther",
    18: "Job",
    19: "Mga Awit",
    20: "Mga Kawikaan",
    21: "Mangangaral",
    22: "Awit ni Solomon",
    23: "Isaias",
    24: "Jeremias",
    25: "Mga Panaghoy",
    26: "Ezekiel",
    27: "Daniel",
    28: "Oseas",
    29: "Joel",
    30: "Amos",
    31: "Obadias",
    32: "Jonas",
    33: "Mikas",
    34: "Nahum",
    35: "Habakuk",
    36: "Sofonias",
    37: "Hagai",
    38: "Zacarias",
    39: "Malakias",
    40: "Mateo",
    41: "Marcos",
    42: "Lucas",
    43: "Juan",
    44: "Mga Gawa",
    45: "Mga Taga-Roma",
    46: "1 Mga Taga-Corinto",
    47: "2 Mga Taga-Corinto",
    48: "Mga Taga-Galacia",
    49: "Mga Taga-Efeso",
    50: "Mga Taga-Filipos",
    51: "Mga Taga-Colosas",
    52: "1 Mga Taga-Tesalonica",
    53: "2 Mga Taga-Tesalonica",
    54: "1 Timoteo",
    55: "2 Timoteo",
    56: "Tito",
    57: "Filemon",
    58: "Mga Hebreo",
    59: "Santiago",
    60: "1 Pedro",
    61: "2 Pedro",
    62: "1 Juan",
    63: "2 Juan",
    64: "3 Juan",
    65: "Judas",
    66: "Pahayag",
}

MALAYALAM_BOOK_NAMES = {
    1: "ഉല്പത്തി",
    2: "പുറപ്പാട്",
    3: "ലേവ്യപുസ്തകം",
    4: "സംഖ്യാപുസ്തകം",
    5: "ആവർത്തനം",
    6: "യോശുവ",
    7: "ന്യായാധിപന്മാർ",
    8: "രൂത്ത്",
    9: "1 ശമൂവേൽ",
    10: "2 ശമൂവേൽ",
    11: "1 രാജാക്കന്മാർ",
    12: "2 രാജാക്കന്മാർ",
    13: "1 ദിനവൃത്താന്തം",
    14: "2 ദിനവൃത്താന്തം",
    15: "എസ്രാ",
    16: "നെഹെമ്യാവ്",
    17: "എസ്ഥേർ",
    18: "ഇയ്യോബ്",
    19: "സങ്കീർത്തനങ്ങൾ",
    20: "സദൃശവാക്യങ്ങൾ",
    21: "സഭാപ്രസംഗി",
    22: "ഉത്തമഗീതം",
    23: "യെശയ്യാവ്",
    24: "യിരെമ്യാവ്",
    25: "വിലാപങ്ങൾ",
    26: "യെഹെസ്കേൽ",
    27: "ദാനിയേൽ",
    28: "ഹോശേയ",
    29: "യോവേൽ",
    30: "ആമോസ്",
    31: "ഓബദ്യാവ്",
    32: "യോനാ",
    33: "മീഖാ",
    34: "നഹൂം",
    35: "ഹബക്കൂക്ക്",
    36: "സെഫന്യാവ്",
    37: "ഹഗ്ഗായി",
    38: "സെഖര്യാവ്",
    39: "മലാഖി",
    40: "മത്തായി",
    41: "മർക്കൊസ്",
    42: "ലൂക്കൊസ്",
    43: "യോഹന്നാൻ",
    44: "അപ്പൊസ്തലന്മാരുടെ പ്രവൃത്തികൾ",
    45: "റോമർ",
    46: "1 കൊരിന്ത്യർ",
    47: "2 കൊരിന്ത്യർ",
    48: "ഗലാത്യർ",
    49: "എഫെസ്യർ",
    50: "ഫിലിപ്പിയർ",
    51: "കൊലൊസ്സ്യർ",
    52: "1 തെസ്സലൊനീക്യർ",
    53: "2 തെസ്സലൊനീക്യർ",
    54: "1 തിമൊഥെയൊസ്",
    55: "2 തിമൊഥെയൊസ്",
    56: "തീത്തൊസ്",
    57: "ഫിലേമോൻ",
    58: "എബ്രായർ",
    59: "യാക്കോബ്",
    60: "1 പത്രൊസ്",
    61: "2 പത്രൊസ്",
    62: "1 യോഹന്നാൻ",
    63: "2 യോഹന്നാൻ",
    64: "3 യോഹന്നാൻ",
    65: "യൂദാ",
    66: "വെളിപാട്",
}

MARATHI_BOOK_NAMES = {
    1: "उत्पत्ती",
    2: "निर्गम",
    3: "लेवीय",
    4: "गणना",
    5: "अनुवाद",
    6: "यहोशवा",
    7: "शास्ते",
    8: "रूथ",
    9: "1 शमुवेल",
    10: "2 शमुवेल",
    11: "1 राजे",
    12: "2 राजे",
    13: "1 इतिहास",
    14: "2 इतिहास",
    15: "एज्रा",
    16: "नहेम्या",
    17: "एस्तेर",
    18: "ईयोब",
    19: "स्तोत्रसंहिता",
    20: "नीतिसूत्रे",
    21: "उपदेशक",
    22: "गीतरत्न",
    23: "यशया",
    24: "यिर्मया",
    25: "विलापगीत",
    26: "यहेज्केल",
    27: "दानीएल",
    28: "होशेय",
    29: "योएल",
    30: "आमोस",
    31: "ओबद्या",
    32: "योना",
    33: "मीखा",
    34: "नहूम",
    35: "हबक्कूक",
    36: "सफन्या",
    37: "हाग्गय",
    38: "जखऱ्या",
    39: "मलाखी",
    40: "मत्तय",
    41: "मार्क",
    42: "लूक",
    43: "योहान",
    44: "प्रेषितांची कृत्ये",
    45: "रोमकरांस",
    46: "1 करिंथकरांस",
    47: "2 करिंथकरांस",
    48: "गलतीकरांस",
    49: "इफिसकरांस",
    50: "फिलिप्पैकरांस",
    51: "कलस्सैकरांस",
    52: "1 थेस्सलनीकाकरांस",
    53: "2 थेस्सलनीकाकरांस",
    54: "1 तीमथ्य",
    55: "2 तीमथ्य",
    56: "तीत",
    57: "फिलेमोन",
    58: "इब्री लोकांस",
    59: "याकोब",
    60: "1 पेत्र",
    61: "2 पेत्र",
    62: "1 योहान",
    63: "2 योहान",
    64: "3 योहान",
    65: "यहूदा",
    66: "प्रकटीकरण",
}

HAITIAN_BOOK_NAMES = {
    1: "Jenèz",
    2: "Egzòd",
    3: "Levitik",
    4: "Nonb",
    5: "Deteronòm",
    6: "Jozye",
    7: "Jij",
    8: "Rit",
    9: "1 Samyèl",
    10: "2 Samyèl",
    11: "1 Wa",
    12: "2 Wa",
    13: "1 Kwonik",
    14: "2 Kwonik",
    15: "Esdras",
    16: "Neyemi",
    17: "Estè",
    18: "Jòb",
    19: "Sòm",
    20: "Pwovèb",
    21: "Eklezyas",
    22: "Chante Salomon",
    23: "Ezayi",
    24: "Jeremi",
    25: "Lamantasyon",
    26: "Ezekyèl",
    27: "Danyèl",
    28: "Oze",
    29: "Jowèl",
    30: "Amòs",
    31: "Abdyas",
    32: "Jonas",
    33: "Miche",
    34: "Nawoum",
    35: "Abakouk",
    36: "Sofoni",
    37: "Aje",
    38: "Zakari",
    39: "Malachi",
    40: "Matye",
    41: "Mak",
    42: "Lik",
    43: "Jan",
    44: "Travay Apot yo",
    45: "Women",
    46: "1 Korentyen",
    47: "2 Korentyen",
    48: "Galat",
    49: "Efezyen",
    50: "Filipyen",
    51: "Kolosyen",
    52: "1 Tesalonikyen",
    53: "2 Tesalonikyen",
    54: "1 Timote",
    55: "2 Timote",
    56: "Tit",
    57: "Filemon",
    58: "Ebre",
    59: "Jak",
    60: "1 Pyè",
    61: "2 Pyè",
    62: "1 Jan",
    63: "2 Jan",
    64: "3 Jan",
    65: "Jid",
    66: "Revelasyon",
}

SERBIAN_BOOK_NAMES = {
    1: "Постање",
    2: "Излазак",
    3: "Левитска",
    4: "Бројеви",
    5: "Поновљени закон",
    6: "Исус Навин",
    7: "Судије",
    8: "Рута",
    9: "1 Самуилова",
    10: "2 Самуилова",
    11: "1 Књига о царевима",
    12: "2 Књига о царевима",
    13: "1 Дневника",
    14: "2 Дневника",
    15: "Јездра",
    16: "Немија",
    17: "Јестира",
    18: "Јов",
    19: "Псалми",
    20: "Приче Соломонове",
    21: "Проповедник",
    22: "Песма над песмама",
    23: "Исаија",
    24: "Јеремија",
    25: "Плач Јеремијин",
    26: "Језекиљ",
    27: "Данило",
    28: "Осија",
    29: "Јоило",
    30: "Амос",
    31: "Авдија",
    32: "Јона",
    33: "Михеј",
    34: "Наум",
    35: "Авакум",
    36: "Софонија",
    37: "Агеј",
    38: "Захарија",
    39: "Малахија",
    40: "Матеј",
    41: "Марко",
    42: "Лука",
    43: "Јован",
    44: "Дела апостолска",
    45: "Римљанима",
    46: "1 Коринћанима",
    47: "2 Коринћанима",
    48: "Галатима",
    49: "Ефесцима",
    50: "Филипљанима",
    51: "Колошанима",
    52: "1 Солуњанима",
    53: "2 Солуњанима",
    54: "1 Тимотеју",
    55: "2 Тимотеју",
    56: "Титу",
    57: "Филимону",
    58: "Јеврејима",
    59: "Јаковљева",
    60: "1 Петрова",
    61: "2 Петрова",
    62: "1 Јованова",
    63: "2 Јованова",
    64: "3 Јованова",
    65: "Јудина",
    66: "Откривење",
}

MAORI_BOOK_NAMES = {
    1: "Kenehi",
    2: "Ekoruha",
    3: "Rewitiku",
    4: "Tauanga",
    5: "Tiuteronomi",
    6: "Hohua",
    7: "Kaiwhakariterite",
    8: "Rutu",
    9: "1 Hamuera",
    10: "2 Hamuera",
    11: "1 Kingi",
    12: "2 Kingi",
    13: "1 Whakapapa",
    14: "2 Whakapapa",
    15: "Ehara",
    16: "Nehemia",
    17: "Ehetere",
    18: "Hopa",
    19: "Waiata",
    20: "Whakatauki",
    21: "Kaikauwhau",
    22: "Waiata a Horomona",
    23: "Ihaia",
    24: "Heremaia",
    25: "Tangi a Heremaia",
    26: "Ehekiera",
    27: "Raniera",
    28: "Hohea",
    29: "Hoera",
    30: "Amoho",
    31: "Opatia",
    32: "Hona",
    33: "Mika",
    34: "Nahumu",
    35: "Hapakuku",
    36: "Hepania",
    37: "Hakai",
    38: "Hakaraia",
    39: "Maraki",
    40: "Matiu",
    41: "Maka",
    42: "Ruka",
    43: "Hoani",
    44: "Nga Mahi",
    45: "Roma",
    46: "1 Koriniti",
    47: "2 Koriniti",
    48: "Karatia",
    49: "Epeha",
    50: "Piripi",
    51: "Korohe",
    52: "1 Teharonika",
    53: "2 Teharonika",
    54: "1 Timoti",
    55: "2 Timoti",
    56: "Taituha",
    57: "Pirimona",
    58: "Hiperu",
    59: "Hemi",
    60: "1 Pita",
    61: "2 Pita",
    62: "1 Hoani",
    63: "2 Hoani",
    64: "3 Hoani",
    65: "Hura",
    66: "Whakakitenga",
}

GAELIC_BOOK_NAMES = {
    1: "Genesis",
    2: "Ecsodus",
    3: "Lebhiticus",
    4: "Àireamh",
    5: "Deuteronomi",
    6: "Iosua",
    7: "Breitheamhnan",
    8: "Rut",
    9: "1 Samuel",
    10: "2 Samuel",
    11: "1 Rìghrean",
    12: "2 Rìghrean",
    13: "1 Eachdraidh",
    14: "2 Eachdraidh",
    15: "Esra",
    16: "Nehemiah",
    17: "Ester",
    18: "Iob",
    19: "Sailm",
    20: "Gnàth-fhacail",
    21: "An t-Searmonaiche",
    22: "Dàn Sholaimh",
    23: "Isaiah",
    24: "Ieremiah",
    25: "Tuireadh",
    26: "Eseciel",
    27: "Daniel",
    28: "Hosea",
    29: "Ioel",
    30: "Amos",
    31: "Obadiah",
    32: "Ionah",
    33: "Micah",
    34: "Nahum",
    35: "Habacuc",
    36: "Sephaniah",
    37: "Hagai",
    38: "Sechariah",
    39: "Malachi",
    40: "Mata",
    41: "Marcus",
    42: "Lucas",
    43: "Eòin",
    44: "Gnìomharan",
    45: "Ròmanaich",
    46: "1 Corintianach",
    47: "2 Corintianach",
    48: "Galàtianach",
    49: "Ephèsianach",
    50: "Philipianach",
    51: "Colosianach",
    52: "1 Tesalonianach",
    53: "2 Tesalonianach",
    54: "1 Timòteus",
    55: "2 Timòteus",
    56: "Tìtus",
    57: "Philèmon",
    58: "Eabhraidhich",
    59: "Seumas",
    60: "1 Peadar",
    61: "2 Peadar",
    62: "1 Eòin",
    63: "2 Eòin",
    64: "3 Eòin",
    65: "Iùdas",
    66: "Taisbeanadh",
}

LOW_GERMAN_BOOK_NAMES = {
    1: "1 Mose",
    2: "2 Mose",
    3: "3 Mose",
    4: "4 Mose",
    5: "5 Mose",
    6: "Josua",
    7: "Richters",
    8: "Ruth",
    9: "1 Samuel",
    10: "2 Samuel",
    11: "1 Könige",
    12: "2 Könige",
    13: "1 Chronik",
    14: "2 Chronik",
    15: "Esra",
    16: "Nehemia",
    17: "Esther",
    18: "Hiob",
    19: "Psalme",
    20: "Spräkweed",
    21: "Predja",
    22: "Hoheleed",
    23: "Jesaja",
    24: "Jeremia",
    25: "Klageleeda",
    26: "Hesekiel",
    27: "Daniel",
    28: "Hosea",
    29: "Joel",
    30: "Amos",
    31: "Obadja",
    32: "Jona",
    33: "Micha",
    34: "Nahum",
    35: "Habakuk",
    36: "Zefanja",
    37: "Haggai",
    38: "Sacharja",
    39: "Maleachi",
    40: "Matäus",
    41: "Markus",
    42: "Lukas",
    43: "Johannes",
    44: "Aposteljeschicht",
    45: "Röma",
    46: "1 Korinta",
    47: "2 Korinta",
    48: "Galata",
    49: "Efesa",
    50: "Filippa",
    51: "Kolossa",
    52: "1 Tessalonicha",
    53: "2 Tessalonicha",
    54: "1 Timoteus",
    55: "2 Timoteus",
    56: "Titus",
    57: "Filemon",
    58: "Hebräa",
    59: "Jakobus",
    60: "1 Petrus",
    61: "2 Petrus",
    62: "1 Johannes",
    63: "2 Johannes",
    64: "3 Johannes",
    65: "Judas",
    66: "Openboarunk",
}

CHURCH_SLAVONIC_BOOK_NAMES = {
    1: "Бытїе",
    2: "Исхо́дъ",
    3: "Леvі́тъ",
    4: "Числа",
    5: "Второзако́ніе",
    6: "Іису́съ Наvі́нъ",
    7: "Кни́га Судей",
    8: "Ру́ѳь",
    9: "1 Ца́рствъ",
    10: "2 Ца́рствъ",
    11: "3 Ца́рствъ",
    12: "4 Ца́рствъ",
    13: "1 Паралипоме́нонъ",
    14: "2 Паралипоме́нонъ",
    15: "Е́здра",
    16: "Неемі́а",
    17: "Есѳи́рь",
    18: "І́овъ",
    19: "Псалти́рь",
    20: "При́тчи",
    21: "Екклесіа́стъ",
    22: "Пѣ́снь Пѣ́сней",
    23: "Иса́їа",
    24: "Іеремі́а",
    25: "Пла́чъ Іереміи́нъ",
    26: "Іезекі́иль",
    27: "Даніи́лъ",
    28: "О́сіа",
    29: "Іои́ль",
    30: "Амо́съ",
    31: "Авді́й",
    32: "Іо́на",
    33: "Міхе́й",
    34: "Нау́мъ",
    35: "Авваку́мъ",
    36: "Софо́ніа",
    37: "Агге́й",
    38: "Заха́ріа",
    39: "Малахі́а",
    40: "Матѳе́й",
    41: "Ма́ркъ",
    42: "Лука́",
    43: "Іоа́ннъ",
    44: "Дѣя́нїя Апо́столовъ",
    45: "Ри́мляномъ",
    46: "1 Корі́нѳяномъ",
    47: "2 Корі́нѳяномъ",
    48: "Гала́томъ",
    49: "Ефесе́йомъ",
    50: "Філіппі́йцємъ",
    51: "Колоссе́йомъ",
    52: "1 Солу́няномъ",
    53: "2 Солу́няномъ",
    54: "1 Тімоѳе́ю",
    55: "2 Тімоѳе́ю",
    56: "Ті́ту",
    57: "Філімо́ну",
    58: "Евре́йомъ",
    59: "Іа́кова",
    60: "1 Петра́",
    61: "2 Петра́",
    62: "1 Іоа́нна",
    63: "2 Іоа́нна",
    64: "3 Іоа́нна",
    65: "Іу́ды",
    66: "Апока́ліпсисъ",
}

KURDISH_SORANI_BOOK_NAMES = {
    1: "پەیدابوون",
    2: "دەرچوون",
    3: "لێڤییەکان",
    4: "ژمارەکان",
    5: "دووتەرۆنۆمی",
    6: "یەشوع",
    7: "ڕابەران",
    8: "ڕوت",
    9: "١ ساموئێل",
    10: "٢ ساموئێل",
    11: "١ پاشایان",
    12: "٢ پاشایان",
    13: "١ پوختەی مێژوو",
    14: "٢ پوختەی مێژوو",
    15: "عەزرا",
    16: "نەحەمیا",
    17: "ئەستەر",
    18: "ئەیوب",
    19: "زەبوورەکان",
    20: "پەندەکان",
    21: "وتووێژکار",
    22: "گۆرانیی گۆرانییەکان",
    23: "ئیشایا",
    24: "یەرەمیا",
    25: "شینەکان",
    26: "حەزقیێل",
    27: "دانیال",
    28: "هۆشەع",
    29: "یوئێل",
    30: "عامۆس",
    31: "عۆبەدیا",
    32: "یۆنس",
    33: "میکا",
    34: "ناحووم",
    35: "حەبەقووق",
    36: "سەفەنیا",
    37: "حەجەی",
    38: "زەکەریا",
    39: "مەلاکی",
    40: "مەتا",
    41: "مەرقۆس",
    42: "لووقا",
    43: "یۆحەنا",
    44: "کردارەکان",
    45: "ڕۆمییەکان",
    46: "١ کۆرنسییەکان",
    47: "٢ کۆرنسییەکان",
    48: "گەلاتییەکان",
    49: "ئەفەسییەکان",
    50: "فیلیپییەکان",
    51: "کۆلۆسییەکان",
    52: "١ تەسالۆنیکییەکان",
    53: "٢ تەسالۆنیکییەکان",
    54: "١ تیمۆساوس",
    55: "٢ تیمۆساوس",
    56: "تیتۆس",
    57: "فلیمۆن",
    58: "عیبرانییەکان",
    59: "یاقوب",
    60: "١ پەترووس",
    61: "٢ پەترووس",
    62: "١ یۆحەنا",
    63: "٢ یۆحەنا",
    64: "٣ یۆحەنا",
    65: "یەهوزا",
    66: "ڕوونکردنەوە",
}

SYRIAC_BOOK_NAMES = {
    1: "ܒܪܝܬܐ",
    2: "ܡܦܩܢܐ",
    3: "ܟܗ̈ܢܐ",
    4: "ܡܢ̈ܝܢܐ",
    5: "ܬܢܝܢ ܢܡܘ̈ܣܐ",
    6: "ܝܫܘܥ ܒܪ ܢܘܢ",
    7: "ܕ̈ܝܢܐ",
    8: "ܪܥܘܬ",
    9: "ܫܡܘܐܝܠ ܩܕܡܝܐ",
    10: "ܫܡܘܐܝܠ ܬܪܝܢܐ",
    11: "ܡ̈ܠܟܐ ܩܕܡܝܐ",
    12: "ܡ̈ܠܟܐ ܬܪܝܢܐ",
    13: "ܕܒܪ̈ܝܡܝܢ ܩܕܡܝܐ",
    14: "ܕܒܪ̈ܝܡܝܢ ܬܪܝܢܐ",
    15: "ܥܙܪܐ",
    16: "ܢܚܡܝܐ",
    17: "ܐܣܬܝܪ",
    18: "ܐܝܘܒ",
    19: "ܡܙ̈ܡܘܪܐ",
    20: "ܡ̈ܬܠܐ",
    21: "ܩܘܗܠܬ",
    22: "ܬܫܒ̈ܚܬ ܬܫܒ̈ܚܬܐ",
    23: "ܐܫܥܝܐ",
    24: "ܐܪܡܝܐ",
    25: "ܐ̈ܘܠܝܬ ܕܐܪܡܝܐ",
    26: "ܚܙܩܝܐܝܠ",
    27: "ܕܢܝܐܝܠ",
    28: "ܗܘܫܥ",
    29: "ܝܘܐܝܠ",
    30: "ܥܡܘܣ",
    31: "ܥܘܒܕܝܐ",
    32: "ܝܘܢܢ",
    33: "ܡܝܟ̣ܐ",
    34: "ܢܚܘܡ",
    35: "ܚܒܩܘܩ",
    36: "ܨܦܢܝܐ",
    37: "ܚܓܝ",
    38: "ܙܟ̣ܪܝܐ",
    39: "ܡܠܐܟ̣ܝ",
    40: "ܡܬܝ",
    41: "ܡܪܩܘܣ",
    42: "ܠܘܩܐ",
    43: "ܝܘܚܢܢ",
    44: "ܦܪ̈ܟܣܝܣ",
    45: "ܪ̈ܗܘܡܝܐ",
    46: "ܩܘܪ̈ܢܬܝܐ ܩܕܡܝܬܐ",
    47: "ܩܘܪ̈ܢܬܝܐ ܬܪܝܢܝܬܐ",
    48: "ܓ̈ܠܛܝܐ",
    49: "ܐ̈ܦܣܝܐ",
    50: "ܦ̈ܝܠܝܦܝܣܝܐ",
    51: "ܩ̈ܘܠܣܝܐ",
    52: "ܬ̈ܣ̈ܠܘܢܝܩܝܐ ܩܕܡܝܬܐ",
    53: "ܬ̈ܣ̈ܠܘܢܝܩܝܐ ܬܪܝܢܝܬܐ",
    54: "ܛܝܡܬܐܘܣ ܩܕܡܝܬܐ",
    55: "ܛܝܡܬܐܘܣ ܬܪܝܢܝܬܐ",
    56: "ܛܛܘܣ",
    57: "ܦ̈ܝܠܝܡܘܢ",
    58: "ܥ̈ܒܪ̈ܝܐ",
    59: "ܝܥܩܘܒ",
    60: "ܟ̣ܐܦ̣ܐ ܩܕܡܝܬܐ",
    61: "ܟ̣ܐܦ̣ܐ ܬܪܝܢܝܬܐ",
    62: "ܝܘܚܢܢ ܩܕܡܝܬܐ",
    63: "ܝܘܚܢܢ ܬܪܝܢܝܬܐ",
    64: "ܝܘܚܢܢ ܬܠܝܬ̣ܝܬ̣ܐ",
    65: "ܝܗܘܕܐ",
    66: "ܓ̣ܠܝܢܐ",
}

GOTHIC_BOOK_NAMES = {
    1: "Genesis",
    2: "Exodus",
    3: "Leviticus",
    4: "Numeri",
    5: "Deuteronomium",
    6: "Iesua",
    7: "Stauans",
    8: "Ruþ",
    9: "1 Samuhel",
    10: "2 Samuhel",
    11: "1 Þiudane",
    12: "2 Þiudane",
    13: "1 Garaihtei",
    14: "2 Garaihtei",
    15: "Aizra",
    16: "Naiumia",
    17: "Aisþaur",
    18: "Iob",
    19: "Psalmam",
    20: "Spriuhtom",
    21: "Aikklesiastes",
    22: "Liuþ Liuþe",
    23: "Esaeias",
    24: "Iairaimias",
    25: "Gaunoþos",
    26: "Aihzekiel",
    27: "Danihel",
    28: "Ausaie",
    29: "Ioel",
    30: "Amos",
    31: "Abdius",
    32: "Ionas",
    33: "Meika",
    34: "Naum",
    35: "Abbakuk",
    36: "Saifanias",
    37: "Aggaius",
    38: "Zakarias",
    39: "Malakias",
    40: "Matþaius",
    41: "Markus",
    42: "Lukas",
    43: "Iohannes",
    44: "Waurstwa Apaustaule",
    45: "Rumonans",
    46: "1 Kaurinþium",
    47: "2 Kaurinþium",
    48: "Galatium",
    49: "Aifaisius",
    50: "Filippius",
    51: "Kaulaussaium",
    52: "1 Þaissalauneikaium",
    53: "2 Þaissalauneikaium",
    54: "1 Teimauþaiu",
    55: "2 Teimauþaiu",
    56: "Teitu",
    57: "Fileimon",
    58: "Haibraium",
    59: "Iakobu",
    60: "1 Paitrau",
    61: "2 Paitrau",
    62: "1 Iohanne",
    63: "2 Iohanne",
    64: "3 Iohanne",
    65: "Iuda",
    66: "Andhuleins",
}

LANGUAGE_LOOKUPS = {
    "UKR": UKRAINIAN_BOOK_NAMES,
    "RUS": RUSSIAN_BOOK_NAMES,
    "GER": GERMAN_BOOK_NAMES,
    "DEU": GERMAN_BOOK_NAMES,
    "FRE": FRENCH_BOOK_NAMES,
    "SPA": SPANISH_BOOK_NAMES,
    "ESP": SPANISH_BOOK_NAMES,
    "POR": PORTUGUESE_BOOK_NAMES,
    "ITA": ITALIAN_BOOK_NAMES,
    "DAN": DANISH_BOOK_NAMES,
    "SWE": SWEDISH_BOOK_NAMES,
    "NOR": NORWEGIAN_BOOK_NAMES,
    "NL": DUTCH_BOOK_NAMES,
    "FIN": FINNISH_BOOK_NAMES,
    "POL": POLISH_BOOK_NAMES,
    "HUN": HUNGARIAN_BOOK_NAMES,
    "CZE": CZECH_BOOK_NAMES,
    "CES": CZECH_BOOK_NAMES,
    "ROM": ROMANIAN_BOOK_NAMES,
    "RUM": ROMANIAN_BOOK_NAMES,
    "GRE": GREEK_BOOK_NAMES,
    "GRC": GREEK_BOOK_NAMES,
    "TUR": TURKISH_BOOK_NAMES,
    "AFR": AFRIKAANS_BOOK_NAMES,
    "ALB": ALBANIAN_BOOK_NAMES,
    "ALS": ALBANIAN_BOOK_NAMES,
    "ARA": ARABIC_BOOK_NAMES,
    "BAQ": BASQUE_BOOK_NAMES,
    "BEL": BELARUSIAN_BOOK_NAMES,
    "BUL": BULGARIAN_BOOK_NAMES,
    "CHI": CHINESE_BOOK_NAMES,
    "HEB": HEBREW_BOOK_NAMES,
    "KOR": KOREAN_BOOK_NAMES,
    "LAT": LATIN_BOOK_NAMES,
    "VIE": VIETNAMESE_BOOK_NAMES,
    "HIN": HINDI_BOOK_NAMES,
    "TAM": TAMIL_BOOK_NAMES,
    "THA": THAI_BOOK_NAMES,
    "HRV": CROATIAN_BOOK_NAMES,
    "CRO": CROATIAN_BOOK_NAMES,
    "LAV": LATVIAN_BOOK_NAMES,
    "LET": LATVIAN_BOOK_NAMES,
    "CEB": CEBUANO_BOOK_NAMES,
    "SWA": SWAHILI_BOOK_NAMES,
    "TGL": TAGALOG_BOOK_NAMES,
    "MAL": MALAYALAM_BOOK_NAMES,
    "MAR": MARATHI_BOOK_NAMES,
    "HAT": HAITIAN_BOOK_NAMES,
    "SCR": SERBIAN_BOOK_NAMES,
    "SRP": SERBIAN_BOOK_NAMES,
    "MAO": MAORI_BOOK_NAMES,
    "GAE": GAELIC_BOOK_NAMES,
    "GLA": GAELIC_BOOK_NAMES,
    "NDS": LOW_GERMAN_BOOK_NAMES,
    "CHU": CHURCH_SLAVONIC_BOOK_NAMES,
    "CKB": KURDISH_SORANI_BOOK_NAMES,
    "SYR": SYRIAC_BOOK_NAMES,
    "GOT": GOTHIC_BOOK_NAMES,
    "SHU": ARABIC_BOOK_NAMES,
}


def get_book_name(book_elem, book_num, language=None):
    # For English, try XML attributes first
    if language == "ENG":
        bname = book_elem.get("bname", "")
        if bname:
            return bname

        bsname = book_elem.get("bsname", "")
        if bsname:
            return bsname

    # For non-English languages with a lookup table, use that first
    if language and language in LANGUAGE_LOOKUPS:
        return LANGUAGE_LOOKUPS[language].get(
            book_num, BOOK_NAMES.get(book_num, f"Book {book_num}")
        )

    # Fallback: try to extract name from caption in XML
    first_chap = book_elem.find("CHAPTER")
    if first_chap is not None:
        caption = first_chap.find("CAPTION")
        if caption is not None and caption.text:
            caption_text = caption.text.strip()
            if "." in caption_text:
                parts = caption_text.rsplit(".", 1)
                short_name = parts[-1].strip()
                if short_name and len(short_name) < 30:
                    return short_name

    return BOOK_NAMES.get(book_num, f"Book {book_num}")


def parse_xml_bible(xml_path):
    tree = ET.parse(xml_path)
    root = tree.getroot()

    bible_name = root.get("biblename", "Unknown")

    info = root.find("INFORMATION")
    description = ""
    language = None
    if info is not None:
        desc_elem = info.find("description")
        if desc_elem is not None:
            description = desc_elem.text or ""
        lang_elem = info.find("language")
        if lang_elem is not None and lang_elem.text:
            xml_lang = lang_elem.text.strip().upper()
            path_lower = xml_path.lower()
            if xml_lang == "RUS" and (
                "ukrainian" in path_lower or "українська" in path_lower
            ):
                language = "UKR"
            else:
                language = xml_lang

    if not language:
        parts = xml_path.replace("\\", "/").split("/")

        if len(parts) > 1:
            folder_name = parts[1].upper()
            if folder_name == "RUS":
                path_lower = xml_path.lower()
                if "ukrainian" in path_lower or "українська" in path_lower:
                    language = "UKR"
                else:
                    language = "RUS"
            elif folder_name in LANGUAGE_LOOKUPS or folder_name == "ENG":
                language = folder_name

    books = []
    for book_elem in root.findall("BIBLEBOOK"):
        book_num = int(book_elem.get("bnumber", 0))
        book_name = get_book_name(book_elem, book_num, language)
        chapters = []

        for chap_elem in book_elem.findall("CHAPTER"):
            chap_num = int(chap_elem.get("cnumber", 0))
            verses = []

            for vers_elem in chap_elem.findall("VERS"):
                vers_num = int(vers_elem.get("vnumber", 0))
                vers_text = vers_elem.text or ""
                verses.append((vers_num, vers_text))

            chapters.append((chap_num, verses))

        books.append((book_num, book_name, chapters))

    return bible_name, description, books, language


def convert_to_spb(xml_path, output_path):
    bible_name, description, books, language = parse_xml_bible(xml_path)

    abbreviation = "".join(word[0] for word in bible_name.split() if word)

    rtl = "1" if language in ("ARA", "HEB", "SYR", "CKB", "SHU") else ""

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("##spDataVersion:\t1\n")
        f.write(f"##Title:\t{bible_name}\n")
        f.write(f"##Abbreviation:\t{abbreviation}\n")
        f.write(f"##Information:\t{description}\n")
        f.write(f"##RightToLeft:\t{rtl}\n")

        for book_num, book_name, chapters in books:
            f.write(f"{book_num}\t{book_name}\t{len(chapters)}\n")

        f.write("-----\n")

        for book_num, book_name, chapters in books:
            for chap_num, verses in chapters:
                for vers_num, vers_text in verses:
                    verse_id = f"B{book_num:03d}C{chap_num:03d}V{vers_num:03d}"
                    f.write(
                        f"{verse_id}\t{book_num}\t{chap_num}\t{vers_num}\t{vers_text}\n"
                    )

    print(f"Converted '{xml_path}' to '{output_path}'")


def find_xml_files():
    return sorted(glob.glob("**/*.xml", recursive=True))


def pick_option(items, label):
    print(f"\n{label}:\n")
    for i, item in enumerate(items, 1):
        print(f"  {i}. {item}")
    print(f"\n  A. All")
    print(f"  B. Back")
    choice = input("\nChoice: ").strip().lower()
    if choice == "b":
        return None
    if choice == "a":
        return (items, True)
    try:
        idx = int(choice) - 1
        if 0 <= idx < len(items):
            return ([items[idx]], False)
    except ValueError:
        pass
    print("Invalid selection.")
    return None


def group_by_dir(files, depth):
    groups = {}
    for f in files:
        parts = f.replace("\\", "/").split("/")
        if depth < len(parts):
            key = parts[depth]
        else:
            key = os.path.dirname(f)
        groups.setdefault(key, []).append(f)
    return groups


def main():
    all_xml = find_xml_files()

    if not all_xml:
        print("No XML files found in current directory or subdirectories.")
        sys.exit(1)

    top_dirs = sorted(set(f.replace("\\", "/").split("/")[0] for f in all_xml))

    to_convert = []

    while True:
        top_groups = group_by_dir(all_xml, 0)
        result = pick_option(
            sorted(top_groups.keys()),
            f"Select directory ({len(all_xml)} XML files total)",
        )
        if result is None:
            sys.exit(0)
        selected_top, chose_all = result

        level1_files = []
        for t in selected_top:
            level1_files.extend(top_groups.get(t, []))

        if chose_all:
            to_convert = level1_files
            break

        lang_groups = group_by_dir(level1_files, 1)
        if len(lang_groups) <= 1 and len(level1_files) <= 10:
            to_convert = level1_files
            break

        result = pick_option(
            [f"{k} ({len(v)} files)" for k, v in sorted(lang_groups.items())],
            f"Select language/group ({len(level1_files)} XML files)",
        )
        if result is None:
            continue
        selected_langs, chose_all = result

        lang_keys = []
        sorted_langs = sorted(lang_groups.items())
        for sel in selected_langs:
            for k, v in sorted_langs:
                if sel == f"{k} ({len(v)} files)":
                    lang_keys.append(k)
                    break

        level2_files = []
        for k in lang_keys:
            level2_files.extend(lang_groups[k])

        if chose_all:
            to_convert = level2_files
            break

        bible_groups = group_by_dir(level2_files, 2)
        if len(bible_groups) <= 1:
            to_convert = level2_files
            break

        result = pick_option(
            [f"{k} ({len(v)} files)" for k, v in sorted(bible_groups.items())],
            f"Select Bible ({len(level2_files)} XML files)",
        )
        if result is None:
            continue
        selected_bibles, chose_all = result

        bible_keys = []
        sorted_bibles = sorted(bible_groups.items())
        for sel in selected_bibles:
            for k, v in sorted_bibles:
                if sel == f"{k} ({len(v)} files)":
                    bible_keys.append(k)
                    break

        level3_files = []
        for k in bible_keys:
            level3_files.extend(bible_groups[k])

        if chose_all:
            to_convert = level3_files
            break

        if len(level3_files) > 1:
            filenames = [os.path.basename(f) for f in level3_files]
            result = pick_option(
                filenames, f"Select file ({len(level3_files)} XML files)"
            )
            if result is None:
                continue
            selected_files, _ = result
            to_convert = [
                f for f in level3_files if os.path.basename(f) in selected_files
            ]
        else:
            to_convert = level3_files
        break

    if not to_convert:
        print("No files selected.")
        sys.exit(0)

    print(f"\n{'=' * 50}")
    print(f"Will convert {len(to_convert)} XML file(s):")
    print(f"{'=' * 50}")
    for f in to_convert:
        print(f"  {f}")
    print()
    confirm = input("Continue? (Y/n): ").strip().lower()
    if confirm and confirm != "y":
        print("Cancelled.")
        sys.exit(0)
    print()

    for xml_file in to_convert:
        base_name = os.path.splitext(xml_file)[0]
        output_file = f"{base_name}.spb"
        convert_to_spb(xml_file, output_file)

    print(f"\nDone! Converted {len(to_convert)} file(s).")


if __name__ == "__main__":
    main()
