package org.churchpresenter.crossword.ui

internal object Strings {
    const val navPrev = "←"
    const val navNext = "→"
    const val newLevel = "+ New Level"
    const val jumpTo = "Jump to"
    const val editorPlaceholder = "Enter puzzle plaintext…"
    const val importTxt = "Import .txt…"
    const val loadXwp = "Load .xwp"
    const val exportXwp = "Export .xwp"
    const val fixReorder = "Fix/Reorder"
    const val exportAll = "Export All"
    const val decodeAll = "Decode All"
    const val previewEmpty = "Enter clues to see preview"
    const val cluesAcross = "Across"
    const val cluesDown = "Down"
    const val windowTitle = "ChurchPresenter Cross Editor"
    const val prevLevelTip = "Go to previous level"
    const val nextLevelTip = "Go to next level"
    const val noLevels = "No levels"
    const val newLevelTip = "Create a new empty level and open it for editing"
    const val importTxtTip = "Import a .txt plaintext puzzle file from disk into this level"
    const val loadPlaintextTitle = "Load Plaintext"
    const val loadXwpTip = "Decode and load the saved .xwp file for this level back into the editor"
    const val exportXwpTip = "Encode and save this level as a .xwp file for use in the presenter"
    const val fixReorderTip = "Build the crossword grid and renumber clues in reading order " +
        "(top→bottom, left→right). Also converts simplified formats to " +
        "standard layout."
    const val exportAllTip = "Export all levels to .xwp files in one go, skipping any that are invalid or still unedited"
    const val decodeAllTip = "Decode all .xwp files in the encoded/ folder back to plaintext .txt files"
    const val invalidFormat = "Invalid puzzle format."
    const val replacePlaceholders = "Replace the placeholder clues before exporting."
    const val cannotExportInvalid = "Cannot export: clues don't form a valid crossword — run Fix/Reorder first."
    const val cannotReorderInvalid = "Cannot reorder: invalid puzzle format."
    const val cannotReorderNoWords = "Cannot reorder: no words could be placed."
    const val noPlaintextLevels = "No plaintext levels found in puzzles/"
    const val noXwpFiles = "No .xwp files found in encoded/"

    fun levelPosition(level: Int, position: Int, total: Int) = "Level $level  ($position / $total)"
    fun templatesWarning(levels: String) = "⚠ Level $levels: clues not yet entered"
    fun unexportedWarning(levels: String) = "⚠ Level $levels not exported"
    fun imported(name: String) = "Imported $name"
    fun levelNotFound(level: Int) = "Level $level not found — edit to create it"
    fun newLevelCreated(level: Int) = "New level $level — edit to begin"
    fun exported(level: Int) = "Exported level$level.xwp"
    fun xwpNotFound(level: Int) = "level$level.xwp not found in encoded/"
    fun loadedEncoded(level: Int) = "Loaded encoded level $level"
    fun decodeFailed(level: Int) = "Failed to decode level$level.xwp"
    fun reorderedUnplaced(unplaced: Int) = "Reordered — $unplaced clue(s) not in puzzle"
    fun reorderedAll(count: Int) = "Reordered — all $count clues placed"
    fun exportedCount(count: Int) = "Exported $count level(s)"
    fun skippedCount(count: Int) = ", $count skipped (invalid/unplaceable)"
    fun decodedCount(count: Int) = "Decoded $count level(s)"
    fun failedCount(count: Int) = ", $count failed"
}
