/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_churchpresenter_app_churchpresenter_composables_DeckLinkManager */

#ifndef _Included_org_churchpresenter_app_churchpresenter_composables_DeckLinkManager
#define _Included_org_churchpresenter_app_churchpresenter_composables_DeckLinkManager
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jobjectArray JNICALL Java_org_churchpresenter_app_churchpresenter_composables_DeckLinkManager_nativeListDevices
  (JNIEnv *, jclass);

JNIEXPORT jboolean JNICALL Java_org_churchpresenter_app_churchpresenter_composables_DeckLinkManager_nativeOpen
  (JNIEnv *, jclass, jint, jint, jint);

JNIEXPORT void JNICALL Java_org_churchpresenter_app_churchpresenter_composables_DeckLinkManager_nativeSendFrame
  (JNIEnv *, jclass, jint, jintArray, jint, jint);

JNIEXPORT jboolean JNICALL Java_org_churchpresenter_app_churchpresenter_composables_DeckLinkManager_nativeStartScheduledPlayback
  (JNIEnv *, jclass, jint, jdouble);

JNIEXPORT void JNICALL Java_org_churchpresenter_app_churchpresenter_composables_DeckLinkManager_nativeScheduleFrame
  (JNIEnv *, jclass, jint, jintArray, jint, jint);

JNIEXPORT void JNICALL Java_org_churchpresenter_app_churchpresenter_composables_DeckLinkManager_nativeStopPlayback
  (JNIEnv *, jclass, jint);

JNIEXPORT void JNICALL Java_org_churchpresenter_app_churchpresenter_composables_DeckLinkManager_nativeClose
  (JNIEnv *, jclass, jint);

JNIEXPORT jintArray JNICALL Java_org_churchpresenter_app_churchpresenter_composables_DeckLinkManager_nativeGetOutputInfo
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
