/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_churchpresenter_app_churchpresenter_composables_DeckLinkManager */

#ifndef _Included_org_churchpresenter_app_churchpresenter_composables_DeckLinkManager
#define _Included_org_churchpresenter_app_churchpresenter_composables_DeckLinkManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_churchpresenter_app_churchpresenter_composables_DeckLinkManager
 * Method:    nativeListDevices
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_churchpresenter_app_churchpresenter_composables_DeckLinkManager_nativeListDevices
  (JNIEnv *, jclass);

/*
 * Class:     org_churchpresenter_app_churchpresenter_composables_DeckLinkManager
 * Method:    nativeOpen
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_org_churchpresenter_app_churchpresenter_composables_DeckLinkManager_nativeOpen
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_churchpresenter_app_churchpresenter_composables_DeckLinkManager
 * Method:    nativeSendFrame
 * Signature: ([III)V
 */
JNIEXPORT void JNICALL Java_org_churchpresenter_app_churchpresenter_composables_DeckLinkManager_nativeSendFrame
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     org_churchpresenter_app_churchpresenter_composables_DeckLinkManager
 * Method:    nativeStartScheduledPlayback
 * Signature: (ID)Z
 */
JNIEXPORT jboolean JNICALL Java_org_churchpresenter_app_churchpresenter_composables_DeckLinkManager_nativeStartScheduledPlayback
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     org_churchpresenter_app_churchpresenter_composables_DeckLinkManager
 * Method:    nativeScheduleFrame
 * Signature: ([III)V
 */
JNIEXPORT void JNICALL Java_org_churchpresenter_app_churchpresenter_composables_DeckLinkManager_nativeScheduleFrame
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     org_churchpresenter_app_churchpresenter_composables_DeckLinkManager
 * Method:    nativeStopPlayback
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_churchpresenter_app_churchpresenter_composables_DeckLinkManager_nativeStopPlayback
  (JNIEnv *, jclass);

/*
 * Class:     org_churchpresenter_app_churchpresenter_composables_DeckLinkManager
 * Method:    nativeClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_churchpresenter_app_churchpresenter_composables_DeckLinkManager_nativeClose
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
